genome/analysis-workflows

- strelka-job.yml
- strelka.cwl
This closes #8.  It depends on genome/docker-strelka-cwl#1.
> Example strelka workflow and example job YAML to run it.

- varscan/samtools_mpileup.cwl
- varscan/varscan_processsomatic.cwl
- varscan/varscan_somatic.cwl
- varscan/workflow-inputs.yaml
- varscan/workflow.cwl
Includes:
- samtools mpileup (with output marked "streamable")
- varscan somatic
- varscan processSomatic
> A CWL workflow for running Varscan Somatic detection.

- mutect/1.interval_list
- mutect/2.interval_list
- mutect/3.interval_list
- mutect/index-input.yml
- mutect/index.cwl
- mutect/merge.cwl
- mutect/mutect.cwl
- mutect/mutect_and_index.cwl
- mutect/workflow-inputs.yml
- mutect/workflow.cwl
Here's a first version of a workflow for running Mutect.
> A CWL mutect workflow.

- pipeline.cwl
Combines detect_variants with alignment (assuming #40, #51, and #52).
> Initial somatic pipeline.

- detect_variants/detect_variants.cwl
- pipeline.cwl
- strelka/strelka-job.yml
- strelka/strelka.cwl
- strelka/workflow.cwl
Not quite tested, since my machine doesn't seem to have enough RAM to satisfy Strelka's detection.
Closes #54.
> Convert pipeline to use Strelka2.

- qc/collect_alignment_summary_metrics.cwl
- qc/collect_hs_metrics.cwl
- qc/collect_insert_size_metrics.cwl
- qc/samtools_flagstat.cwl
- qc/verify_bam_id.cwl
- qc/workflow_exome.cwl
I should that I did not expose any of the optional inputs to these tools at this point. I will wait to do so until we know what the desired parameters are.
> Workflow for exome QC

- detect_variants/vep.cwl
This PR addresses #46 and #45.
> Some changes to the VEP CWL.

- pipeline.cwl
These should've been part of #66.
> Add a few more brackets around some secondaryFile extensions.

- example_data/detect_variants/detect_variants.yaml
- example_data/qc/workflow_exome_normal.yaml
- example_data/qc/workflow_exome_tumor.yaml
Add example data files for QC and detect_variants to run on the MGI Arvados platform.
> Example data for QC and Detect Variants.

- detect_variants/combine_variants.cwl
- detect_variants/detect_variants.cwl
- detect_variants/select_variants.cwl
- pindel/cat_all.cwl
- pindel/cat_out.cwl
- pindel/get_chromosome_list.cwl
- pindel/grep.cwl
- pindel/pindel.cwl
- pindel/pindel_cat.cwl
- pindel/somaticfilter.cwl
- pindel/workflow.cwl
- pindel/workflow.yml
This PR implements pindel workflow parallelized by chromosome to detect_variants workflow. Pindel runs reasonably fast by parallelizing by chromosome. The largest chromosome 1 (249 mb) can finish within 1.5 hrs.
> Add pindel workflow to detect_variants

- qc/collect_hs_metrics.cwl
- qc/workflow_exome.cwl
> Add per_target_coverage as an optional parameter to collect_hs_metrics

- strelka/strelka.cwl
the output directory is not part of the output path
> Strelka Output Paths

- example_data/pindel/pindel_exome.yaml
An example arvados yaml file for pindel.
> Pindel Arvados Example

- .travis.yml
This should run `cwltool --validate` on each CWL file on master and in PRs.
> Run CWL validation with Travis CI.

- pindel/pindel.cwl
- pindel/somaticfilter.cwl
This PR is to have a workaround for an Arvados filepath bug. The change was tested fine on my laptop.
> Workaround for an Arvados filepath bug

- strelka/strelka.cwl
- strelka/workflow.cwl
Update the paths to the strelka2 output files.
> Strelka2 Output 

- exome_alignment.cwl
basic exome alignment and qc pipeline.
> Exome Alignment

- pindel/get_bam_index.cwl
This one has an entrypoint Arvados likes.
> Change samtools docker image source

- mutect/mutect.cwl
- mutect/mutect_and_index.cwl
- mutect/workflow.cwl
- panel_of_normals/combine_variants.cwl
- panel_of_normals/workflow.cwl
Allow mutect to run in abstract_detection_mode for panel of normals. workflow for making a panel of normals VCF.
> Panel of Normals

- detect_variants/select_variants.cwl
- detect_variants/split_interval_list.cwl
- varscan/set_filter_status.cwl
In my test this ended up using about 4.5GB of RAM, so 6 should give it a little room.
> Add a resource request for several Java-based steps.

- detect_variants/combine_docm.cwl
- detect_variants/combine_variants.cwl
- detect_variants/detect_variants.cwl
- detect_variants/select_variants.cwl
- docm/GATK_haplotype_caller.cwl
- docm/docm_filter.cwl
- docm/workflow.cwl
This PR is to add docm to detect_variant workflow.
> Add docm to detect_variants workflow

- detect_variants/combine_variants.cwl
- detect_variants/fp_filter.cwl
- detect_variants/select_variants.cwl
- detect_variants/vep.cwl
- mutect/mutect.cwl
- pindel/pindel.cwl
- varscan/set_filter_status.cwl
Add necessary resource requests to run the full exome and reduce warnings.
> Full Exome Resource Requests

- detect_variants/detect_variants.cwl
- detect_variants/select_variants.cwl
- example_data/detect_variants/detect_variants.yaml
Add hard filter option to limit VCF to PASS only variants.
> Hard Filter VCF

- detect_variants/detect_variants.cwl
- detect_variants/variants_to_table.cwl
Initial version of a VCF to TSV converter.
> VCF to TSV

- detect_variants/detect_variants.cwl
- mutect/mutect.cwl
- mutect/workflow.cwl
- panel_of_normals/workflow.cwl
Output of my test run with a PON input specified is currently in `/gscmnt/gc2764/cad/tmooney/toil_test/out/dv/`.
> Add optional Panel-of-Normals VCF input to DetectVariants.

- fp_filter/normalize_variants.cwl
- fp_filter/workflow.cwl
- mutect/workflow.cwl
- pindel/remove_end_tags.cwl
- pindel/workflow.cwl
- varscan/workflow.cwl
> Left-Align Indels before running the FP filter.

- unaligned_bam_to_bqsr/index_cram.cwl
- unaligned_bam_to_bqsr/workflow.cwl
> Index the final CRAM file after alignment.

- .travis.yml
This is an attempt to resolve the error reported in [this travis-ci build](https://travis-ci.org/genome/cancer-genomics-workflow/builds/230403347).
> Upgrade pip before installing packages.

- detect_variants/detect_variants.cwl
- detect_variants/vep.cwl
> Add option for adding HGVS annotation to VEP

- detect_variants/detect_variants.cwl
- detect_variants/vep.cwl
- example_data/detect_variants/vep.yaml
- example_data/detect_variants/vep_without_local_cache.yaml
This supersedes PR #171. It implements option B of #170.
> Fix hgvs parameter

- detect_variants/detect_variants.cwl
- example_data/detect_variants/detect_variants.yaml
- mutect/mutect.cwl
- mutect/workflow.cwl
- varscan/varscan.cwl
- varscan/varscan_processsomatic.cwl
- varscan/varscan_somatic.cwl
- varscan/workflow.cwl
So we can change parameters via input yaml files. This PR relies on https://github.com/genome/docker-cle/pull/39.
> Add several parameter inputs to varscan and mutect cwl

- detect_variants/detect_variants.cwl
- pvacseq/bam_readcount.cwl
Add step in toil cwl to run normal bam_readcount.
This relies on https://github.com/genome/docker-cle/pull/44
> Add step to run normal bam_readcount

- example_data/rnaseq/workflow.yaml
> example rnaseq workflow YAML.

- example_data/cle_IDT_exome_template.yml
This is the latest and best CLE IDT exome assay yaml that will be used in production. Merging this PR will have to wait until IT's full test with this yml succeeds.
> Add cle_IDT_exome_template.yml to example_data

- detect_variants/tumor_only_detect_variants.cwl
- varscan/germline_workflow.cwl
- varscan/varscan_germline.cwl
So far this only uses VarScan for detection.  Depends on genome/docker-cle#51.
> Start of a single-sample detect variants workflow.

- example_data/detect_variants/detect_variants.yaml
Moved VCF files and auxiliary files to GMS allocations.
> Update detect_variants example data.

- qc/collect_alignment_summary_metrics.cwl
- qc/collect_gc_bias_metrics.cwl
- qc/collect_hs_metrics.cwl
- qc/collect_insert_size_metrics.cwl
- qc/workflow_exome.cwl
- qc/workflow_wgs.cwl
> Add metric accumulation level and the reference to insert size metrics.

- detect_variants/germline_combine_variants.cwl
- detect_variants/tumor_only_detect_variants.cwl
- docm/germline_gatk_haplotypecaller.cwl
- docm/germline_workflow.cwl
- fp_filter/fp_filter.cwl
- fp_filter/workflow.cwl
- varscan/germline_workflow.cwl
This makes it more similar to the Somatic Varscan workflow.
> Add FP Filter to Varscan, add DoCM to tumor-only DV workflow.

- unaligned_bam_to_bqsr/downsample.cwl
- unaligned_bam_to_bqsr/downsample_workflow.cwl
Initial revision of a downsample unaligned BAM to aligned BAM workflow.
> Downsample Alignment

- detect_variants/coding_variant_filter.cwl
- detect_variants/tumor_only_detect_variants.cwl
This adds some additional filtering and updates a few defaults.
~This depends on #228.~ Rebased after merge of #228.
> Updates to Single-Sample DV based on Initial Tests

- wgs_alignment.cwl
This will require making a combined Docker image for both worklfows.
> New WGS alignment+QC CWL to mirror exome_alignment.cwl

- wgs_workflow.cwl
Here's a first version of a new combined tumor-only WGS workflow.
* Several of the optional DetectVariants inputs were left out as inputs here.  I wanted to avoid proliferating the default values in multiple places, since we seem to be relying on them for now.
* Is `wgs_workflow.cwl` a good name for this?
* I wasn't sure if it made sense to use the same interval list for both `CollectWgsMetrics` and variant detection.  They're two parameters in this version.
> Workflow for running WGS Alignment, QC, and Variant Detection.

- detect_variants/vep.cwl
This also brings the master version of vep.cwl in line with the toil_compatibility branch.
> Update vep.cwl to use v90

- detect_variants/gatk_haplotypecaller.cwl
- detect_variants/gatk_haplotypecaller_iterator.cwl
GATK likes to have this index around. 😄
> Add tabix index as secondary file for dbSNP parameter.

- qc/collect_gc_bias_metrics.cwl
- qc/collect_wgs_metrics.cwl
I'm a little confused how we got to this point without having removed these!
> Remove DockerRequirements from two QC tools.

- detect_variants/af_filter.cwl
- detect_variants/tumor_only_detect_variants.cwl
- detect_variants/vep.cwl
- example_data/detect_variants/vep.yaml
> Use custom gnomAD VCF to calculate AF. Filter on AF instead of MAX_AF

- exome_workflow.cwl
We had been running one workflow after the other--this combines the two!
> Add an Alignment+QC & Variant Detection combined exome workflow.

- exome_workflow.cwl
It's a lot more useful if it's connected to something :)
> Pass the `hgvs_annotation` input to detect variants workflow.

- docm/docm_filter.cwl
- docm/workflow.cwl
Refer to https://github.com/genome/docker-cle/pull/71.  Make workflow input change for docm_filter.pl change that fix a docm bug.
> Make input change to reflect docm_filter.pl change

- detect_variants/gnomADe_AF_filter.cwl
- detect_variants/tumor_only_detect_variants.cwl
- exome_workflow.cwl
This is an alternative to #257.
> Use a custom gnomad VCF in the exome workflow.

- rnaseq/stringtie.cwl
- rnaseq/workflow.cwl
This will output a tsv file with gene expression data.
> Add -A option to StringTie

- detect_variants/tumor_only_detect_variants.cwl
- exome_workflow.cwl
- qc/workflow_exome.cwl
hard code boolean values that can not be set with process_inputs.pl creating the YAML input files.
> MDS Processing Profile 04262018

- process_inputs.pl
> Add process_inputs.pl to PP branch

- umi_alignment/align.cwl
- umi_alignment/alignment_workflow.cwl
- umi_alignment/call_duplex_consensus.cwl
- umi_alignment/clip_overlap.cwl
- umi_alignment/duplex_seq_metrics.cwl
- umi_alignment/extract_umis.cwl
- umi_alignment/fastq_to_bam.cwl
- umi_alignment/filter_consensus.cwl
- umi_alignment/group_reads.cwl
- umi_alignment/mark_illumina_adapters.cwl
- umi_alignment/realign.cwl
- umi_alignment/workflow.cwl
Generally follows the analysis guide on #204.
> First version of a UMI alignment workflow.

- README.md
- umi_alignment/alignment_workflow.cwl
- umi_alignment/duplex_alignment_workflow.cwl
- umi_alignment/duplex_workflow.cwl
- umi_alignment/merge.cwl
- umi_alignment/molecular_alignment_workflow.cwl
- umi_alignment/molecular_workflow.cwl
This introduces a merge step after the initial alignment before the UMI grouping and consensus.
> Handle multiple instrument data in UMI workflows

- unaligned_bam_to_bqsr/align_and_tag.cwl
> upping ram, per issue #294

- exome_alignment.cwl
- exome_workflow.cwl
- germline_exome_workflow.cwl
- qc/collect_hs_metrics.cwl
- qc/workflow_exome.cwl
- umi_alignment/molecular_qc_workflow.cwl
Added in 2 new inputs to fix issue #316
> 2 new input parameters in collect_hs_metrics

- exome_alignment.cwl
- exome_workflow.cwl
- germline_exome_workflow.cwl
- qc/collect_insert_size_metrics.cwl
- qc/workflow_exome.cwl
- qc/workflow_wgs.cwl
- umi_alignment/molecular_qc_workflow.cwl
- wgs_alignment.cwl
- wgs_workflow.cwl
This would close issue #315, except that the new workflow in #312 will also need to be updated, depending which PR gets merged first.
> Save the insert size histogram during QC.

- somatic_exome_workflow.cwl
Combines two alignment workflows with the detect variants workflow.
> First version of a somatic exome workflow.

- detect_variants/vep.cwl
> Add --transcript_version to vep.cwl to include version in transcript ids

- detect_variants/germline_detect_variants.cwl
- germline_exome_workflow.cwl
This workflow is now more similar to the tumor-only DV workflow.
Closes #314.
> Extract Germline DV to a Subworkflow and Add Coding-Only and Region Filtering

- germline_wgs_workflow.cwl
Based on the Exome workflow, but with the WGS alignment process instead!
> New Germline WGS workflow for alignment, QC, HaplotypeCaller, VEP.

- germline_wgs_workflow.cwl
This should help make everyone else's travis builds succeed!
> Update parameter name to "dbsnp_vcf"

- definitions/tools/pon_combine_variants.cwl
- panel_of_normals/workflow.cwl
Refer to https://github.com/genome/analysis-workflows/pull/396
> Rename/Relocate panel_of_normals combine_variant

- definitions/tools/combine_variants.cwl
- detect_variants/detect_variants.cwl
Note there is a same named one under panel_of_normals that uses different parameters
> Move combine_variant to def/tools, add docker

- definitions/subworkflows/mutect.cwl
- detect_variants/detect_variants.cwl
- panel_of_normals/workflow.cwl
renamed to `definitions/subworkflows/mutect.cwl`
> moved mutect/workflow.cwl to subworkflows with rename

- definitions/tools/pvacfuse.cwl
- definitions/tools/pvacseq.cwl
- definitions/tools/pvacvector.cwl
Depends on https://github.com/griffithlab/docker-pvactools/pull/4
> Use latest pvactools docker version

- bisulfite/pileup.cwl
- germline_wgs_workflow.cwl
need this update to solve some issues
> new version of biscuit has changed params

- definitions/pipelines/rnaseq.cwl
- definitions/subworkflows/bam_to_trimmed_fastq_and_hisat_alignments.cwl
- definitions/tools/bam_to_fastq.cwl
- definitions/tools/generate_qc_metrics.cwl
- definitions/tools/hisat2_align.cwl
- definitions/tools/kallisto.cwl
- definitions/tools/stringtie.cwl
- definitions/tools/trim_fastq.cwl
- Simplifies the strand parameter. Javascript expressions pass parameters based on strandedness. missing or nonsensical values assume unstranded libraries (should we assume first instead?)
- makes a few small updates to requirements fields to address 
https://github.com/genome/analysis-workflows/issues/501
> simplifying strand parameter

- example_data/exome_workflow.tgz.md5
Include example data that can be used with #496
> Added minimal clinvar vcf and index

- definitions/tools/gatk_haplotype_caller.cwl
When it's slightly lower, breaching the requested amount is practically guaranteed!
> Set the memory request higher than the JVM memory limit.

- definitions/pipelines/exome.cwl
- definitions/pipelines/exome_alignment.cwl
- definitions/pipelines/gathered_somatic_exome.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/wgs.cwl
- definitions/pipelines/wgs_alignment.cwl
- definitions/subworkflows/hs_metrics.cwl
- definitions/subworkflows/molecular_qc.cwl
- definitions/subworkflows/qc_exome.cwl
- definitions/subworkflows/qc_wgs.cwl
- definitions/types/labelled_file.yml
- example_data/germline_exome.yaml
- example_data/germline_wgs.yaml
- example_data/somatic_exome.yaml
This incorporates HS metrics into the QC process.
It's the first time we're using a custom type in our workflows.  I propose herein that we have a new `types` directory under definitions for holding these custom types.  It's important for the proper function of the workflow that this definition be referenced from a central place rather than repeated in several modules, because identical-looking types are not inherently interpreted as being the same.
> New subworkflow for running HS metrics.

- definitions/tools/pindel.cwl
- definitions/tools/vep.cwl
This is meant to address #565 and #567 in a quick way, based solely on what were sufficient to get a single project through!
> Some resource tweaks to Pindel and VEP.

- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/wgs.cwl
- definitions/pipelines/wgs_alignment.cwl
- definitions/subworkflows/qc_wgs.cwl
- definitions/tools/deeptools_bamcoverage.cwl
This PR is part of #467.
This wrapper includes almost all of the optional parameters available to the tool, but they're not currently being exposed to the larger workflows.  We should discuss which options are needed and/or any defaults to set.
> New tool: `bamCoverage` from deeptools.

- definitions/tools/add_strelka_gt.cwl
- definitions/tools/collect_gc_bias_metrics.cwl
- definitions/tools/collect_wgs_metrics.cwl
- definitions/tools/combine_variants.cwl
- definitions/tools/downsample.cwl
- definitions/tools/filter_vcf_allele_freq.cwl
- definitions/tools/filter_vcf_cle.cwl
- definitions/tools/filter_vcf_exac.cwl
- definitions/tools/filter_vcf_mapq0.cwl
- definitions/tools/filter_vcf_max_allele_freq.cwl
- definitions/tools/merge_vcf.cwl
- definitions/tools/mutect.cwl
- definitions/tools/pindel.cwl
- definitions/tools/pindel_somatic_filter.cwl
- definitions/tools/pon_combine_variants.cwl
- definitions/tools/position_sort.cwl
- definitions/tools/remove_end_tags.cwl
- definitions/tools/samtools_mpileup.cwl
- definitions/tools/set_filter_status.cwl
- definitions/tools/somatic_docm_filter.cwl
- definitions/tools/split_interval_list.cwl
- definitions/tools/varscan_process_somatic.cwl
- definitions/tools/varscan_somatic.cwl
> updating to stable cle docker version

- definitions/tools/deeptools_bamcoverage.cwl
> Increase memory request for deeptools bamcoverage to 16000 MB.

- definitions/tools/biscuit_align.cwl
- definitions/tools/biscuit_markdup.cwl
- definitions/tools/biscuit_pileup.cwl
- definitions/tools/bisulfite_vcf2bed.cwl
> move pipes inline, update to slim docker image

- definitions/tools/name_sort.cwl
> Increase name sort RAM to 16GB.

- definitions/tools/filter_vcf_docm.cwl
needed to use newer cromwell version
> adding RAM requirements to docm filter

- definitions/pipelines/detect_variants.cwl
- definitions/subworkflows/filter_vcf.cwl
- definitions/tools/filter_vcf_depth.cwl
I thought I pushed this yesterday, but apparently did not.  In any case...
> adding depth filter

- definitions/tools/bedgraph_to_bigwig.cwl
- definitions/tools/merge_bams.cwl
- definitions/tools/trim_fastq.cwl
has been tested on a private docker build.  Will be merged after the docker container is merged, built, and tagged:  https://github.com/genome/docker-bisulfite/pull/5
> adding versioned docker image

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/tools/vep.cwl
allows workflows to pick and choose vep plugins to run. 
currently have the same defaults set for all workflows but a future PR will change the plugins used in the germline workflow
> Parameterizing vep plugins

- definitions/tools/optitype_dna.cwl
This is the first commit of our combined optitype prep step and optitype run step for HLA-typing. There are a few issues to discuss, documented in the issues beginning at genome/docker-immuno_tools-cwl#1. In the interest of time, the current form of the script will be added to our repo, then updated after discussion.
> Initial commit of a functional optitype script

- definitions/tools/vep.cwl
adds missing positional argument to the `--plugins` input for vep.cwl
> adding position argument

- definitions/pipelines/gathered_somatic_exome.cwl
> Fix wrong boolean default

- definitions/pipelines/pvacseq.cwl
- definitions/tools/add_vep_fields_to_table.cwl
- definitions/tools/vcf_expression_annotator.cwl
- definitions/tools/vcf_readcount_annotator.cwl
This incorporates @apaul7 's PR https://github.com/griffithlab/VAtools/pull/26
> Upgrade VAtools to latest version 3.1.0

- definitions/tools/add_string_at_line.cwl
- definitions/tools/add_string_at_line_bgzipped.cwl
Please note: this tool won't work on gzipped files so for the VCF I'll have to dig into whether these are gzipped at the point in the workflow that we want to add the CLE disclaimer and add a second version that first `gzcat`s the input_file and then pipes the output to awk.
> New tool to add arbitrary text to a file at a specific line

- definitions/tools/biscuit_pileup.cwl
16GB of RAM has been failing. Doubling to 32GB.
> Update biscuit pileup RAM

- definitions/pipelines/immuno.cwl
- definitions/subworkflows/pvacseq.cwl
- definitions/tools/extract_hla_alleles.cwl
This is the first attempt at making a new immuno workflow, combining 5 of our other workflows. There is some overlap/redundancy between a few of these, but for now we'd like to get a functioning workflow. Reviews focusing on checking all of the inputs would be appreciated, see comments within immuno.cwl, especially in the pvacseq step at the bottom. A test case should also be developed soon.
> New immuno workflow

- definitions/tools/cle_aml_trio_report_alignment_stat.cwl
- definitions/tools/cle_aml_trio_report_coverage_stat.cwl
- definitions/tools/cle_aml_trio_report_full_variants.cwl
These three report cwl are needed for upcoming aml_trio cwl pipeline.
> Add three report cwl for aml_trio

- definitions/pipelines/rnaseq.cwl
- definitions/tools/mark_duplicates_and_sort.cwl
I changed the ASSUME_SORT_ORDER as user defined because the value for ASSUME_SORT_ORDER varies between the rnaseq and somatic_exome pipelines.
> Added ASSUME_SORT_ORDER as an input

- definitions/tools/filter_vcf_somatic_llr.cwl
a few bugfixes related to t/n name swaps and handling of NA characters
> updating to image with bugfixes

- definitions/subworkflows/qc_exome.cwl
> Add in missing StepInputExpressionRequirement.

- definitions/subworkflows/pindel_region.cwl
- definitions/tools/fix_vcf_header.cwl
- definitions/tools/pindel.cwl
- definitions/tools/pindel2vcf.cwl
- definitions/tools/remove_end_tags.cwl
The new cwl based aml_trio pipeline needs pindel region (FLT3 specifically) output.
> Add pindel_region subworkflow

- definitions/pipelines/cle_somatic_exome.cwl
- definitions/pipelines/gathered_cle_somatic_exome.cwl
CLE needs minimum read depth as 20.
> Add filter_minimum_depth input

- definitions/tools/filter_vcf_somatic_llr.cwl
Full commit is here: 
https://github.com/genome/docker-somatic-llr-filter/commit/0e4068562db730c0edfed029a871303c3c0b4d7f
> handle missing or zero depth field in tumor

- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_wgs.cwl
I seem to have missed connecting the vep_plugins array input from the germline exome and wgs pipelines to the germline detect variants sub workflow
> add vep_plugins to pipeline input

- definitions/subworkflows/filter_vcf.cwl
- definitions/subworkflows/filter_vcf_mouse.cwl
This subworkflow's output was being pulled from intermediate steps
> last two VCF filters were not being applied

- definitions/subworkflows/bam_to_bqsr.cwl
- definitions/subworkflows/fastq_to_bqsr.cwl
- definitions/tools/fastq_align_and_tag.cwl
This is similar to the existing `align_and_tag.cwl` but without the `SamToFastq` pipe.  It's the first step to #717.
> A tool to align from FASTQs directly.

- definitions/tools/filter_vcf_somatic_llr.cwl
This combines with #736 to completely supersede #734.
> Update somatic LLR filter version.

- definitions/tools/bam_readcount.cwl
Had a few jobs get killed in the tumor_only wgs pipeline. Upping this to 8g to address that issue
> Upping RAM to 16Gb

- definitions/tools/filter_sv_vcf_depth.cwl
this pr adds the cnv filtering tool for CNVkit and CNVnator.
closes #749
> adding cnv filtering

- definitions/pipelines/cle_aml_trio.cwl
- definitions/pipelines/cle_somatic_exome.cwl
> Add step to add CLE disclaimer text to final output TSV in the CLE pipelines

- definitions/pipelines/cle_aml_trio.cwl
- definitions/pipelines/cle_somatic_exome.cwl
- definitions/pipelines/gathered_cle_aml_trio.cwl
- definitions/pipelines/gathered_cle_somatic_exome.cwl
Make cle_somatic_exome.cwl and cle_aml_trio.cwl to be new mutect compatible
> Modify cle pipeline to be new mutect compatible

- definitions/pipelines/cle_aml_trio.cwl
- definitions/pipelines/cle_somatic_exome.cwl
- definitions/pipelines/gathered_cle_aml_trio.cwl
- definitions/pipelines/gathered_cle_somatic_exome.cwl
Also prepend the cle disclaimer with a `#`
> Add a cle disclaimer version to the final cle reports

- definitions/tools/merge_bams_samtools.cwl
> add threads to merge command

- definitions/tools/filter_vcf_mapq0.cwl
Closes https://github.com/genome/analysis-workflows/issues/796 
See https://github.com/genome/docker-mapq0-filter/pull/2
> bumping version to get bugfix

- definitions/tools/cellranger_count.cwl
- definitions/tools/cellranger_feature_barcoding.cwl
- definitions/tools/cellranger_mkfastq.cwl
- definitions/tools/cellranger_vdj.cwl
updates cellranger cwls to use the new v3.1.0 image
> update to v3.1.0

- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/aml_trio_cle_gathered.cwl
- definitions/pipelines/somatic_exome_cle.cwl
- definitions/pipelines/somatic_exome_cle_gathered.cwl
Dave requests to add CLE disclaimer information to tumor filtered vcf.
> Add cle disclaimer information to tumor filtered vcf

- definitions/pipelines/alignment_wgs_mouse.cwl
- definitions/pipelines/chipseq_alignment_mouse.cwl
- definitions/subworkflows/qc_wgs_mouse.cwl
- definitions/subworkflows/sequence_to_bqsr_mouse.cwl
I only called this mouse because the existing tools used `mouse` in the name, but maybe they could be called something more generic. 😄 
This also converts some of the mouse tools to support File inputs for the reference.
> New alignment_wgs_mouse.cwl for doing non-human alignments.

- example_data/somatic_exome.yaml
Quick fix from trying to run the somatic workflow test just now.
> Add sample names to example YAML.

- .travis.yml
* don't commit if there are no changes; an empty commit gives a non-zero return code and fails the build
> Fixes for doc generation

- .travis.yml
> Add pyyaml dependency

- definitions/pipelines/rnaseq_star_fusion.cwl
- definitions/tools/star_fusion_detect.cwl
Added star fusion detection.
1. changed rnaseq_star_fusion.cwl
TODO:
1. move genome_index to core/
2. update example yaml
3. wiki create custom fusion genome index.
> star_fusion_detect

- definitions/tools/docm_add_variants.cwl
> add cle docker tag

- definitions/tools/pizzly.cwl
> add pizzly docker tag

- definitions/tools/call_duplex_consensus.cwl
- definitions/tools/call_molecular_consensus.cwl
- definitions/tools/clip_overlap.cwl
- definitions/tools/duplex_seq_metrics.cwl
- definitions/tools/extract_umis.cwl
- definitions/tools/fastq_to_bam.cwl
- definitions/tools/filter_consensus.cwl
- definitions/tools/group_reads.cwl
- definitions/tools/mark_illumina_adapters.cwl
- definitions/tools/realign.cwl
- definitions/tools/umi_align.cwl
> Dna alignment 1.0.0

- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/aml_trio_cle_gathered.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/subworkflows/gatk_haplotypecaller_iterator.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/tools/gatk_haplotype_caller.cwl
This combined with #844 are steps towards a downsample-and-regenerate-GVCF workflow.
> Add options to the GATK HaplotypeCaller tool.

- definitions/tools/collect_wgs_metrics.cwl
Like #844 and #845 these additional options will be used by a new workflow.
> Collect WGS Metrics: Add optional inputs for mapping and base qualities.

- definitions/tools/pon_combine_variants.cwl
using small gatk 3.6 image for `pon_combine_variants.cwl` tool
similar to #857 #862
> use small gatk image for pon_combine_variants.cwl

- definitions/pipelines/somatic_exome.cwl
Added doc line to somalier_vcf input
> Added doc line

- definitions/pipelines/somatic_exome.cwl
Added doc lines for several inputs.
> Added doc lines

- definitions/pipelines/immuno.cwl
I updated the rnaseq subworkflow for documentation of the output fields.
> Immuo CWL output doc update2 for somatic_exome/exome_alignment_and_qc

- definitions/pipelines/downsample_and_recall.cwl
- definitions/pipelines/gathered_downsample_and_recall.cwl
- definitions/subworkflows/gatk_haplotypecaller_iterator.cwl
For taking existing CRAMs and re-running HaplotypeCaller on downsampled versions thereof.
> A downsample and re-call pipeline.

- definitions/subworkflows/vcf_eval_concordance.cwl
- definitions/tools/somatic_concordance_graph.cwl
There is a need to make plot/graph of somatic concordance cwl outputs. This PR is to add the step of plot_output to the workflow. 
Refer to https://jira.ris.wustl.edu/browse/CI-481
> Add Somatic Concordance Graph

- definitions/tools/kallisto.cwl
The strandedness params are swapped, as discussed at length in slack.  This fix should resolve the issue.
> correct kallisto strand params

- definitions/pipelines/downsample_and_recall.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/subworkflows/gatk_haplotypecaller_iterator.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/tools/gatk_haplotype_caller.cwl
First part of genome/covid-19#20.
> Expose ploidy option to the GATK HaplotypeCaller.

- definitions/tools/interval_list_expand.cwl
> Tool to expand interval lists

- definitions/pipelines/alignment_wgs_mouse.cwl
- definitions/pipelines/chipseq_alignment_mouse.cwl
- definitions/subworkflows/sequence_to_bqsr_mouse.cwl
They're using the same tool for which the trimming options were already added!
> Add the trimming options to so-called "mouse" alignment steps.

- definitions/tools/sequence_align_and_tag.cwl
> Pass the first FASTQ rather than a literal string.

- definitions/tools/varscan_somatic.cwl
resolves https://github.com/genome/analysis-workflows/issues/109
> give varscan 2 cores

- example_data/rnaseq/workflow_star_fusion.yaml
Update reference paths for star_fusion_workflow
> update star_fusion paths

- definitions/tools/pvacbind.cwl
- definitions/tools/pvacfuse.cwl
- definitions/tools/pvacseq.cwl
- definitions/tools/pvacvector.cwl
https://hub.docker.com/repository/docker/griffithlab/pvactools/general
> Upgrade pvactools docker versions to 1.5.10

- definitions/pipelines/alignment_exome.cwl
- definitions/pipelines/alignment_wgs.cwl
- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/aml_trio_cle_gathered.cwl
- definitions/pipelines/chipseq.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_gvcf.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/germline_wgs_gvcf.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_cle.cwl
- definitions/pipelines/somatic_exome_cle_gathered.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/pipelines/tumor_only_exome.cwl
- definitions/pipelines/tumor_only_wgs.cwl
- definitions/subworkflows/bam_to_bqsr.cwl
- definitions/subworkflows/bam_to_bqsr_no_dup_marking.cwl
- definitions/subworkflows/downsampled_alignment.cwl
- definitions/subworkflows/fastq_to_bqsr.cwl
- definitions/subworkflows/sequence_to_bqsr.cwl
This permits any number of known sites files to be included.
Closes #868.
> Replace specific BQSR inputs with known_sites array input.

- definitions/pipelines/tumor_only_wgs.cwl
- example_data/tumor_only_wgs.yaml
Updates interval list params to more closely resemble those in the other workflows.  Also exposes a few missing params, and adds a test yaml
> updates intervals, adds missing params and test yaml

- definitions/tools/pvacbind.cwl
- definitions/tools/pvacfuse.cwl
- definitions/tools/pvacseq.cwl
- definitions/tools/pvacvector.cwl
This version significantly reduces runtime for MHCflurry.
> Upgrade to version 1.5.13

- definitions/pipelines/immuno.cwl
- definitions/pipelines/rnaseq.cwl
- definitions/pipelines/rnaseq_star_fusion.cwl
- definitions/pipelines/rnaseq_star_fusion_with_xenosplit.cwl
- definitions/subworkflows/qc_wgs.cwl
- definitions/subworkflows/qc_wgs_nonhuman.cwl
- definitions/tools/bam_to_bigwig.cwl
Bigwig generation for the following pipelines
1. Chip/ATAC Seq Human pipeline
2. RNA Seq pipeline
3. RNA Seq STAR Fusion pipeline
4. RNA Seq STAR Fusion Xenosplit pipeline
> Bigwig step for Chipseq Human pipeline, RNA seq pipelines

- definitions/tools/manta_somatic.cwl
This updates the manta tool to the latest version. Inputs/outputs are the same. There are a few bug fixes and speed optimizations. Reported expected 5-10% increase and potentially a 50% increase in speed. 
https://github.com/Illumina/manta/releases/
> manta to version 1.5.0 -> 1.6.0

- definitions/tools/bedtools_intersect.cwl
updated bedtools to version 2.27.1
> updated bedtools to version 2.29.2

- definitions/tools/cellranger_count.cwl
- definitions/tools/cellranger_feature_barcoding.cwl
- definitions/tools/cellranger_mkfastq.cwl
- definitions/tools/cellranger_vdj.cwl
This PR updates cellranger to the latest version. I've had a few builds succeed using the cwl.
> update cellranger to version 6.0.0

- definitions/tools/filter_vcf_docm.cwl
Found another place where this sample extraction code breaks (see https://github.com/genome/analysis-workflows/pull/1020).  Did a quick grep through the repo and don't see any others at present.
> updating regex to handle edge case headers

- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/immuno.cwl
> add padding to target_intervals input for germline exome pipeline

- definitions/tools/homer_tag_directory.cwl
Updates version and adds some documentation on how to mount the appropriate volumes
> updating homer docker version

- definitions/tools/filter_sv_vcf_blocklist_bedpe.cwl
updating the tabix path in the sv blocklist filter script to match the path in the docker image
> update tabix path to match docker image

- .github/workflows/update_docs.yml
Not sure of a good way to test this before tossing it out here...
> Migrate documentation generator to github actions.

- .github/workflows/main.yml
- definitions/pipelines/rnaseq_star_fusion_with_xenosplit.cwl
- definitions/subworkflows/cram_to_cnvkit.cwl
python3.7 is about to go EOL, so let's switch to 3.10.
> Update python and cwltool version for testing CWL syntax
