- strelka-job.yml
- strelka.cwl
The runtime will inform the tool how many cores it has to work with.
> Number of CPUs should be a runtime argument, not an input.

- strelka.cwl
I did a trial with:
```yaml
coresMin: 4
coresMax: 8
```
and it (unsurprisingly) used 4 to run in our trial.  This PR sets a minimum of 8 with no upper bound.
> Set min cores for strelka.

- varscan/varscan_processsomatic.cwl
- varscan/varscan_somatic.cwl
- varscan/workflow.cwl
We can't use `ENTRYPOINT` or `streamable` at present, so this adds a helper script to stream the `mpileup` output into VarScan and revises the workflow accordingly.
> Updates for Arvados-compatibility

- detect_variants/combine_variants.cwl
- detect_variants/detect_variants.cwl
- detect_variants/fp_filter.cwl
- detect_variants/index.cwl
- detect_variants/merge.cwl
- detect_variants/select_variants.cwl
- mutect/mutect.cwl
- mutect/mutect_and_index.cwl
- mutect/workflow.cwl
- strelka/process_vcf.cwl
- strelka/strelka.cwl
- strelka/workflow.cwl
- varscan/bgzip_and_index.cwl
- varscan/samtools_mpileup.cwl
- varscan/set_filter_status.cwl
- varscan/varscan.cwl
- varscan/varscan_somatic.cwl
- varscan/workflow.cwl
The spec looks like it supports either format, but our cwl-runner prefers the array form.
> Specify all secondary file suffixes as arrays.

- unaligned_bam_to_bqsr/name_sort.cwl
Seems like we ought to have a tmp space specification, too. (How much we need is likely related to the size of the input.)
> Reduce sambamba memory to 12G; specify the resource request in CWL.

- detect_variants/combine_variants.cwl
- detect_variants/select_variants.cwl
- example_data/pipeline.yaml
- mutect/mutect.cwl
- varscan/set_filter_status.cwl
@susannasiebert  is this what you had in mind for the yaml?
I have not tested this since it appears the Docker daemon is not running on the shell node:
```
jwalker@shell:~/git/arvados_trial$ arvados-cwl-runner --project-uuid=testx-j7d0g-h48gaxtcg7tfsgl --output-name "HCC1395 Exome GRCh38DH 1" --no-wait --debug pipeline.cwl pipeline.yml
/usr/bin/arvados-cwl-runner 1.0.20161017193526, arvados-python-client 0.1.20161017101604, cwltool 1.0.20161007181528
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Unhandled error, try again with --debug for more information:
Command '['docker', 'images', '--no-trunc', '--all']' returned non-zero exit status 1
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/cwltool/main.py", line 702, in main …
```
> initial version of example pipeline yaml

- unaligned_bam_to_bqsr/apply_bqsr.cwl
Update the output of apply_bqsr to use an array instead of string for secondaryFiles.
> One more secondaryFiles as string to array conversion.

- detect_variants/detect_variants.cwl
- detect_variants/fp_filter.cwl
- mutect/mutect.cwl
- mutect/mutect_and_index.cwl
- mutect/workflow.cwl
- qc/collect_alignment_summary_metrics.cwl
- qc/collect_hs_metrics.cwl
- qc/collect_insert_size_metrics.cwl
- qc/samtools_flagstat.cwl
- qc/workflow_exome.cwl
- strelka/strelka.cwl
- strelka/workflow.cwl
- unaligned_bam_to_bqsr/apply_bqsr.cwl
- unaligned_bam_to_bqsr/workflow.cwl
GATK does not output a .bam.bai suffix but rather only .bai suffix. Account for this in downstream secondaryFiles that use the BQSR BAM file
> BAM index(.bai) suffix 

- pvacseq/bam-readcount.cwl
The helper.pl script in this CWL is mostly taken from https://github.com/ernfrid/fpfilter-tool/blob/master/fpfilter.pl. I was able to successfully run this CWL on some HCC1395 data but the resulting output files where empty. I might've not used the correct combination of files but I'm not sure.
This CWL will need to be wrapped/combined with a different step to run these on the different BAMs and output an file list yml for pVAC-Seq.
> CWL to run bam-readcount on a VCF

- pindel/pindel.cwl
- pindel/pindel_cat.cwl
- pindel/workflow.cwl
A few more places need `"^.bai"` to go along with the alternate naming standard.
> Switch expected Bam Index Name for Pindel Workflow

- pindel/get_bam_index.cwl
- pindel/pindel.cwl
- pindel/pindel_cat.cwl
- pindel/workflow.cwl
Currently it is hard to figure out the path of bam secondary files aka .bai. This PR is an alternative way to work around the issue and keep arvados pipeline test running. We can refactor this once a solution is found in the future.
> Make bam index files and use them as normal/tumor.bam.bai

- strelka/add_gt.cwl
This worked for me with `cwltool`... hopefully it is similarly successful in our larger workflow!
> Strelka2 gzips its outputs, so expect that in the subsequent step.

- fp_filter/fp_filter.cwl
Provide the paths to the location of bam-readcount and samtools rather than hard-coding it in the fpfilter.pl script.
This is required before this is merged:
https://github.com/genome/docker-cle/pull/27
> FP filter paths

- detect_variants/detect_variants.cwl
- detect_variants/merge.cwl
- detect_variants/select_variants.cwl
- docm/workflow.cwl
- fp_filter/fp_filter.cwl
- fp_filter/workflow.cwl
- mutect/mutect.cwl
- mutect/workflow.cwl
- pindel/workflow.cwl
- strelka/workflow.cwl
- varscan/workflow.cwl
I moved the hard filter, bgzip and index into the fp_filter/workflow.cwl.
In addition, I attempted to add an optional `output_vcf_basename` parameter that can be used to keep the names of the per-caller VCFs from conflicting. However, that doesn't work as I expected.
Any feedback on this would be great. I'm open to other ideas or ways of accomplishing:
#131 #133 #134
> Per variant caller VCF

- rnaseq/align.cwl
- rnaseq/bam_to_fastq.cwl
- rnaseq/hisat2_align.cwl
- rnaseq/merge.cwl
- rnaseq/workflow.cwl
This represents step 1 of #144.
One quirk of this version of the implementation: the `reference_index` parameter should point to a file whose name matches the name of the index files but without the extensions (`.1.bt` - `.8.bt`).  This placeholder file can be empty or have whatever contents, but should be small since it will be copied by `toil` alongside the other index files.
(To run, this currently depends on genome/docker-rnaseq#1 to provide the necessary environment.)
> Start of an RnaSeq workflow: Alignment

- unaligned_bam_to_bqsr/align_and_tag.cwl
- unaligned_bam_to_bqsr/apply_bqsr.cwl
- unaligned_bam_to_bqsr/bam_to_cram.cwl
- unaligned_bam_to_bqsr/bqsr.cwl
- unaligned_bam_to_bqsr/mark_duplicates_and_sort.cwl
- unaligned_bam_to_bqsr/merge.cwl
- unaligned_bam_to_bqsr/name_sort.cwl
- unaligned_bam_to_bqsr/revert_to_fastq.cwl
- unaligned_bam_to_bqsr/workflow.cwl
These changes are based on the Dockerfile introduced in genome/docker-unaligned-to-bqsr#1.
Closes #156.
> Updates to `unaligned_bam_to_bqsr` workflow for toil compatibility.

- unaligned_bam_to_bqsr/mark_duplicates_and_sort.cwl
This step tells Java to use 16GB heap and sambamba to use 18GB, so make sure there's enough to handle both of those plus overhead.
> Set mark duplicates memory request to 40 GB.

- rnaseq/align.cwl
- rnaseq/hisat2_align.cwl
- rnaseq/workflow.cwl
This uses `scatterMethod: dotproduct`, so each `instrument_data_bam` parameter must have a corresponding `read_group_id` and array of `read_group_fields` listed in the same order.
Closes #159.
> Add read-group tag support to the HISAT2 CWL.

- strelka/add_gt.cwl
So the real GT can be added to strelka output vcf. This PR relies on https://github.com/genome/docker-cle/pull/40.
> Use add_strelka_gt.pl

- rnaseq/align.cwl
- rnaseq/trim_fastq.cwl
- rnaseq/workflow.cwl
This uses genome/docker-rnaseq#2 to add read-trimming to the workflow.
> Add a read trimming step to RnaSeq alignment.

- unaligned_bam_to_bqsr/align.cwl
- unaligned_bam_to_bqsr/align_and_tag.cwl
CWL changes to support piping of Picard SamToFastq into BWA-MEM as interleaved FASTQ.
Requires https://github.com/genome/docker-dna-alignment/pull/3
> DNA Alignment: Pipe Interleaved FASTQ

- example_data/unaligned_bam_to_bqsr/workflow_no_dup_marking.yml
The dbsnp, known indels and milles/1kg indel paths have been updated to the new location in the GMS. Merging to toil_compatibility.
> Update paths to example data files

- detect_variants/add_bam_readcount_to_vcf.cwl
- detect_variants/detect_variants.cwl
- detect_variants/tumor_only_detect_variants.cwl
- example_data/cle_IDT_exome_template.yml
- pvacseq/bam_readcount.cwl
Add a step to run add_bam_readcount_to_vcf_helper.py so AD, AF, DP info from bam_readcount can be added to vcf format fields. A real toil test is running now.
> Add step to run add_bam_readcount_to_vcf_helper.py

- unaligned_bam_to_bqsr/mark_duplicates_and_sort.cwl
- unaligned_bam_to_bqsr/workflow.cwl
Keep the Picard MarkDuplicates metrics file for later QC.
> Keep MarkDups metrics file.

- unaligned_bam_to_bqsr/downsample_workflow.cwl
keep the mark dups metrics file when running the downsampled workflow.
> Keep MarkDup Metrics for Downsample

- detect_variants/add_bam_readcount_to_vcf.cwl
- detect_variants/detect_variants.cwl
- detect_variants/tumor_only_detect_variants.cwl
- docm/germline_workflow.cwl
- docm/single_sample_docm_filter.cwl
- example_data/detect_variants/add_bam_readcount_to_vcf.yaml
I ran a test for the add_bam_readcount_to_vcf.cwl with the included add_bam_readcount_to_vcf.yaml. I can move the test data files to the example_data directory, if desired. I haven't tested the changes to the tumor only workflow.
> Add add_bam_readcount_to_vcf to tumor_only workflow

- exome_alignment.cwl
* Save the metrics from MarkDuplicates.
* Allow specifying the metric accumulation level for Picard for QC.
> Update exome_alignment.cwl with a few new features from the underlying workflows

- detect_variants/gatk_haplotypecaller.cwl
- detect_variants/gatk_haplotypecaller_iterator.cwl
GATK makes these index files automatically, so might as well retain them.
> Keep the tabix index for the gVCF in the GATK HC output.

- exome_alignment.cwl
- qc/collect_hs_metrics.cwl
- qc/workflow_exome.cwl
There is no boolean flag at the top level alignment workflow, but we can
hardcode a true value in any processing-profiles that need it.  (The `CwlPipeline` wrapper in genome still doesn't easily support boolean flags as inputs, so we'd probably hardcode the value, anyway.)
This addresses #247.
> Add optional parameter for base metric output in CollectHsMetrics.

- detect_variants/detect_variants.cwl
- detect_variants/tumor_only_detect_variants.cwl
This brings it in line with the somatic workflow and satisfies the needs of the HaplotypeCaller.
> Add .tbi as secondaryFile for the DoCM VCF in tumor-only Detect Variants

- detect_variants/gatk_haplotypecaller.cwl
This is to get around a bug in 3.6.  See also genome/docker-cle#64.
> Point to specific versioned GATK JAR for HaplotypeCaller.

- detect_variants/coding_variant_filter.cwl
- detect_variants/exac_filter.cwl
- detect_variants/max_af_filter.cwl
VEP fails to output anything in this case, which breaks downstream steps.  This uses genome/docker-cle#66 to skip running and copy the input file to the output.
> Skip running VEP filters on empty VCF files.

- unaligned_bam_to_bqsr/name_sort.cwl
12G > 12000M, so this was unlikely to work out before.
> Add a little buffer space between system memory limit and sambamba param.

- unaligned_bam_to_bqsr/bqsr.cwl
The `.tbi` indexes are already required for the inputs to the workflow.cwl in this directory, so let's pass them along!
Closes #259.
> Expect known_sites files to be tabix indexed.

- example_data/exome_workflow.tgz.md5
The tar archive was truncated and added an md5.
> Second attempt: Fix gnomADe test vcf

- README.md
- umi_alignment/alignment_workflow.cwl
- umi_alignment/duplex_alignment_workflow.cwl
- umi_alignment/duplex_workflow.cwl
- umi_alignment/merge.cwl
- umi_alignment/molecular_alignment_workflow.cwl
- umi_alignment/molecular_qc_workflow.cwl
- umi_alignment/molecular_workflow.cwl
This PR includes the entirety of #281.  Beyond that, it adds CRAM conversion and introduces a new workflow to run the exome QC after the alignment process has completed.
> CRAM and QC for molecular UMI workflow

- detect_variants/vep.cwl
This is a holdover from an earlier version that was `cat`ting files to help build the command-line.
> Remove ShellCommandRequirement from vep.cwl

- exome_alignment.cwl
- exome_workflow.cwl
- germline_exome_workflow.cwl
- qc/collect_hs_metrics.cwl
- qc/workflow_exome.cwl
- umi_alignment/molecular_qc_workflow.cwl
This change makes the per-base and per-target coverage required.
This is part of #297.
> Run CollectHsMetrics with additional coverage targets.

- rnaseq/stringtie.cwl
- rnaseq/workflow.cwl
Added in two optional parameters that can add --rf or --fr flags to stringtie; this should resolve issue #202. Possibly builds on https://github.com/genome/cancer-genomics-workflow/commit/3cd5ee0003faacec8a92a4b50faff89a2d8f5ac9
> Stringtie now accepts strandedness flag

- example_data/exome_workflow.yaml
Changes in #298 introduced some parameters that were not added into the tutorial YAML file, causing it to immediately error out. Added those parameters, pipeline test in the [tutorial](https://confluence.ris.wustl.edu/display/CI/Toil) now works normally.
> added in missing parameters so that the tutorial will work

- rnaseq/workflow.cwl
Travis CI logs from the cwl validator tool showed 2 secondary outputs expected from a tool run from the rnaseq workflow cwl, but the tool itself only generates one output. Removed the unnecessary expected output from the workflow script.
> Removed unused parameter to fix travis validation warning

- qc/collect_hs_metrics.cwl
The `*` in the `glob` led to broadinstitute/cromwell#4004 when testing with cromwell. We already know what value to expect, so use it instead!
> Use the input prefix to construct expected output names.

- detect_variants/detect_variants.cwl
- detect_variants/tumor_only_detect_variants.cwl
- exome_workflow.cwl
- pvacseq/bam_readcount.cwl
- wgs_workflow.cwl
Modified ./pvacseq/bam_readcount.cwl and all upstream dependencies to optionally accept -q (minimum mapping quality) and -b (minimum base quality) flags. Should close issue #214
> Made -q and -b bam_readcount flags user definable

- README.md
This PR might be best merged after the other restructuring has been completed :smile:
> Update README to stop explicitly recommending toil_compatibility branch.

- definitions/pipelines/germline_exome.cwl
- definitions/subworkflows/gatk_haplotypecaller_iterator.cwl
- definitions/tools/gatk_genotypegvcfs.cwl
- definitions/tools/gatk_haplotype_caller.cwl
Original CWL workflow was unable to successfully complete. Was an issue with finding the output file in the `definitions/tools/gatk_haplotype_caller.cwl` step. Unsure what the root cause was but with the help of @tmooney was able to find a workaround. 
Added an input for a `output_file_name` and moved the javascript expression to generate the name based on the input interval up to the `definitions/subworkflows/gatk_haplotypecaller_iterator.cwl` step.
Also added small docker images.
> Updating germline exome workflow to work with cromwell

- definitions/pipelines/somatic_exome.cwl
- definitions/tools/gatherer.cwl
This PR contains a work-in-progress example workaround for several Cromwell bugs preventing final output files from being consolidated into a single directory. To use, add an `output_dir` string parameter to a workflow's inputs file, specifying an absolute path to the directory where final output files should be placed. Add in a step, which runs `/tools/gatherer.cwl`, taking in `output_dir` and `all_files`, an array of all files to be packaged together. A javascript expression is required to work around a bug and parse this input before actually sending it to the tool; see line 338 of `somatic_exome.cwl`. Finally, make sure to add the output of this step, a string array, to the outputs section.
Limitations:
~~Currently does not work with `secondaryFiles`- looking into fixing this~~
All …
> Output gathering

- definitions/tools/bam_to_fastq.cwl
wastes time and may fail on LIMS data that has eland alignment info
> don't validate the bam before fastq creation

- definitions/tools/collect_alignment_summary_metrics.cwl
- definitions/tools/collect_hs_metrics.cwl
- definitions/tools/collect_insert_size_metrics.cwl
- definitions/tools/cram_to_bam.cwl
- definitions/tools/samtools_flagstat.cwl
- definitions/tools/verify_bam_id.cwl
This should help distinguish which QC matches which alignments, especially in cases where more than one CRAM is present (e.g. somatic pipelines).
> Base QC filenames on the CRAM filename.

- definitions/tools/vcf_expression_annotator.cwl
- definitions/tools/vcf_readcount_annotator.cwl
This version of the vcf-annotation-tools package adds a new fatal error to guard against an edge case where the combined bam-readcount output from snvs and indels might contains two entries for the same position (one from the snvs and one from the indels file). After we merge this in, we might encounter workflows where this situation occurs that would subsequently fail where they didn't fail before. If we encounter this situation I would like to change this fatal error to actually handle this case.
@jasonwalker80 given the above information, should we wait to merge this until after I get back from vacation? I would hate for workflows to fail for this reason while I'm not around to add handling for this case.
> Use latest version of the vcf_annotation_tools-cwl docker image

- definitions/pipelines/germline_exome.cwl
Closes #503.
`per_base_intervals` certainly was an odd choice for this!
> Use the target intervals for limiting variants.

- definitions/pipelines/pvacseq.cwl
- definitions/tools/pvacfuse.cwl
- definitions/tools/pvacseq.cwl
- definitions/tools/pvacvector.cwl
This also fixes an incorrect reference to an input to pvacseq.cwl that I discovered buried in the travis-ci warnings.
> Upgrade pVACtools CWLs to latest version 1.1.5

- definitions/pipelines/somatic_exome.cwl
mutect_artifact_detection_mode is false unless otherwise defined at true. This parameter is only set to true when creating a panel of normals.
> Default value 'false' for Panel of Normals Mutect parameter.

- definitions/tools/mark_duplicates_and_sort.cwl
Recently encountered an error message in my workflows:
` /bin/cp: will not overwrite just-created '/gscmnt/gc2547/griffithlab/ebarnell/GTB24/variant_calling/08-0075-1086/mark_dups_metrics.txt' with '/cromwell-executions/somatic_exome.cwl/3ded19a4-f74e-479f-957a-d9c243274e1d/call-gatherer/inputs/1282502474/mark_dups_metrics.txt'`
This should resolve that issue, however it requires modifying the mgibio docker image to accept a 4th argument, something like:
```#!/bin/bash
set -o pipefail
set -o errexit
declare MD_BARCODE_TAG
if [ ! -z "${5}" ]; then
MD_BARCODE_TAG="BARCODE_TAG=${5}"
/usr/bin/java -Xmx16g -jar /opt/picard/picard.jar MarkDuplicates I=$1 O=/dev/stdout ASSUME_SORT_ORDER=queryname METRICS_FILE=$4 QUIET=true COMPRESSION_LEVEL=0 VALIDATION_STRINGENCY=LENIENT "${MD_BARCODE_TAG}" | …
```
> fixes cp error with mark_duplicates

- definitions/subworkflows/bam_to_bqsr.cwl
- definitions/tools/merge_bams_samtools.cwl
- definitions/tools/name_sort.cwl
Since the mark duplicate metrics are saved, we'll want to make sure the files have unique names in cases where multiple alignments are run in a single workflow.
This takes #516 one step further.
> Use the final_name to distinguish intermediate processes, too.

- definitions/tools/merge_bams_samtools.cwl
The bam_to_bqsr subworkflow is passing this input, and it is being referenced.  CWL validation apparently doesn't require it to be defined to do these things, but running the workflow does.
> Define the name input that we're using.

- definitions/subworkflows/cellranger_mkfastq_and_count.cwl
- definitions/tools/cellranger_count.cwl
- definitions/tools/cellranger_mkfastq.cwl
- definitions/tools/cellranger_vdj.cwl
I have the different CWLs I have been using to run different single cell cell ranger analysis. For `cellranger mkfastq`, `cellranger count`, `cellranger vdj`. This is currently using Eddie’s docker image for cellranger v2.2.0 which is hosted on the local private registry.
I also created a subworkflow that currently runs the `mkfastq` and `count` steps for a single sample. I have ran it using the tiny-bcl test data that can be downloaded from 10x Genomics website in about 15 minutes.
> adding the Cell Ranger analysis cwls

- definitions/tools/cellranger_count.cwl
- definitions/tools/cellranger_mkfastq.cwl
- definitions/tools/cellranger_vdj.cwl
updating to the latest version of cellranger. `cellranger` is not added to the path in the new images so have to specify the installation location
> updating cellranger to 3.0.1

- definitions/subworkflows/bam_to_bqsr.cwl
This property is required for the merge step, so making it optional here requires a default.
(This situation triggers warnings but not errors in `cwltool --validate`.)
> Set a default name for the final cram.

- definitions/tools/bqsr.cwl
- definitions/tools/collect_alignment_summary_metrics.cwl
- definitions/tools/collect_gc_bias_metrics.cwl
- definitions/tools/collect_hs_metrics.cwl
- definitions/tools/collect_insert_size_metrics.cwl
- definitions/tools/collect_wgs_metrics.cwl
- definitions/tools/combine_variants.cwl
- definitions/tools/docm_gatk_haplotype_caller.cwl
- definitions/tools/downsample.cwl
- definitions/tools/gatk_genotypegvcfs.cwl
- definitions/tools/germline_combine_variants.cwl
- definitions/tools/normalize_variants.cwl
- definitions/tools/pon_combine_variants.cwl
Since 16000 MB < 16 GB, this was previously telling the JVM to use more memory than was available!
> Allow for some overhead between Java and job memory requests.

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/exome.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/pipelines/wgs.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/tools/vep.cwl
This PR adds the --everything flag as a default argument to vep. Some of the flags it turns on require a cache to be present, so it's now a required parameter in vep.cwl and all upstream files. This also simplifies some of the argument construction logic within vep.cwl. The new flag also includes some AF flags that were previously only added if there was no custom gnomad vcf; since these are now always present, in order to avoid naming collisions within the vcf fields, fields added from the custom file are prefixed with "custom_gnomad"
> Vep everything flag

- definitions/subworkflows/bam_to_trimmed_fastq_and_biscuit_alignments.cwl
- definitions/tools/biscuit_align.cwl
- definitions/tools/biscuit_markdup.cwl
- definitions/tools/biscuit_pileup.cwl
- definitions/tools/bisulfite_vcf2bed.cwl
This PR: 
- adds a bisulfite-strand aware duplicate marking procedure
- fixes the pileup script to reflect the changed params in the newer version of biscuit
- explicitly specifies the v1.3 tag since older versions of the container will not work with this cwl
> adding markdups, fixing pileup

- definitions/pipelines/bisulfite.cwl
- definitions/tools/bisulfite_vcf2bed.cwl
With ditching the perl script in favor of the built-in utility, we now have to pass the reference fasta to this tool.
> passing ref param to bsvcf2bed

- definitions/pipelines/germline_wgs.cwl
- definitions/subworkflows/cnvkit_single_sample.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/tools/cnvkit_vcf_export.cwl
By default, cnvkit outputs results in a .cns file; this subworkflow runs cnvkit and converts the .cns file to a vcf. Additionally, since the base `cnvkit_batch.cwl` tool has different use cases with different requirements, almost all of its input parameters/outputs are optional. Since we know the exact use case of the `single_sample_sv_callers` subworkflow, irrelevant parameters and nonexistent outputs were removed in upstream steps, and a necessary parameter was updated (previously listed as optional).
> Added a subworkflow for cnvkit that returns a vcf

- definitions/tools/deeptools_bamcoverage.cwl
Genome sizes exceed 32-bit integers. They don't seem *that* long 😄
Guess we've been spoiled by friendlier languages that don't cap their integers.  It's all really a string anyway.
> Use a `long` for the genome size instead of an `int`.

- definitions/tools/pindel.cwl
We continue to see pindel jobs dying due to memory errors. Increasing requested memory again to 64 gb; there may be better solutions worth investigating, but for now, this seems to fix the issues.
> Bump up ram to get around errors

- definitions/subworkflows/cnvkit_single_sample.cwl
- definitions/tools/cnvkit_vcf_export.cwl
The `default` field does not seem to allow parameter references/Javascript, so I made a workaround using the `valueFrom` field instead
> Hacked in default vcf name

- definitions/tools/filter_vcf_somatic_llr.cwl
this version includes an edge case bug fix (see https://github.com/genome/docker-somatic-llr-filter/commit/d4804c2d1c1927d4e8a0909a965ceb3855616acd)
> updating to v0.2

- definitions/subworkflows/merge_svs.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/tools/add_sv_population_frequency.cwl
- definitions/tools/smoove.cwl
- definitions/tools/survivor.cwl
this will allow us to merge the results from different sv callers together into a single vcf. And then annotate them with a population frequency of the sv calls.
I have it set up as a separate sub workflow to make it easier for people to run this manually. 
Open to suggestions on naming of files and input variables.
> Adding survivor merge for sv vcfs

- definitions/subworkflows/duplex_alignment.cwl
- definitions/subworkflows/molecular_alignment.cwl
- definitions/subworkflows/molecular_qc.cwl
- definitions/tools/filter_consensus.cwl
The duplex parameters are way too strict for single-molecule consensus calling. Most of the UMI sequencing we do is not designed for consensus calling at all. Rather than ignore the UMIs, make single-molecule consensus reads but relax the parameters to allow nearly all consensus reads of reasonable quality pass.
This should replace PR #599 since the raw alignments are not really needed. 
NOTE: keeping the original alignments is not the right approach unless we implemented UMI-aware duplicate marking. The net effect is similar to this single-molecule consensus calling with relaxed params.
> New Filter Consensus Params for Single-Molecule

- definitions/pipelines/germline_wgs.cwl
- definitions/subworkflows/merge_svs.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/tools/survivor.cwl
This pr does a few things first I added javascript expressions to handle boolean values for inputs into survivor(thanks to @tmooney for the suggestion). That should make it easier to use and understand the survivor parameters in the pipeline.
Second added the `merge_svs.cwl` subworkflow into the `single_sample_sv_caller.cwl` subworkflow.
Third updated the `germline_wgs.cwl` pipeline to pass down the newly required inputs.
Confirmed that the updated `single_sample_sv_caller.cwl` works with a small test bam.
> adding survivor to single_sample_sv_caller.cwl

- definitions/tools/cellranger_count.cwl
- definitions/tools/cellranger_vdj.cwl
Cellranger has an input option for a run id which is used to generate the running directory and is used as an identifier in some of the output files. Initially we had a generic `cellranger_ouput` id to simplify parsing  and consistency across runs. That makes it difficult to easily determine the sample from the result files. This PR helps to fix that.
> use sample name as run id

- definitions/tools/merge_bams.cwl
quick fix because right now, `latest` no longer has samtools, which breaks this. Longer term, we should phase this out in favor of the samtools merge
> peg to versioned docker tag that has the needed software

- definitions/tools/cellranger_atac_count.cwl
this pr adds a cwl that can be used to run cellranger-atac count. I'll end up using this to create a processing_profile to handle single cell atac samples in the GMS.
> adding cellranger-atac count cwl

- definitions/tools/filter_vcf_max_sv_pop_freq.cwl
This tool adds the option to do filtering on the sv population frequency which has been added using the `add_sv_population_frequency.cwl`.
I originally tried running this in a similar fashion to the `filter_vcf_gnomADe_allele_freq.cwl` tool but continued running into memory issues. Had the max requested RAM to 64gb which is the same amount used to annotate the variants in `vep.cwl`. That still had issues and there is no forking option in filter_vep to help. I start taking subsets of the vcf I was using and figured out that the issue is caused by large svs that have a lot of information stored in the consquence tag created by VEP. Using the `--vcf_info_field` I can trick filter_vep to not load the true consequence tag and can filter the svs without issue.  
Not sure if this is the best …
> adding max population frequency filtering

- definitions/tools/bedtools_intersect.cwl
We use GATK select variants for limiting snp/indel variants with an interval list. Select variants does not properly handle SV variants, Bedtools can. Will require calling `intervals_to_bed.cwl` to convert the interval list file to a bed file.
Tried to allow some flexibility with the tool but there are a bunch of options. (https://github.com/arq5x/bedtools2/blob/v2.27.1/docs/content/tools/intersect.rst)
Not sure if it would be useful to have a default output name. As the output file format could be a few different things I thought it would be best for the subworklow that calls `bedtools.cwl` to also provide an output file name. preferably using labelled file type.
> adding bedtools_intersect.cwl

- definitions/pipelines/cle_somatic_exome.cwl
- definitions/pipelines/gathered_cle_somatic_exome.cwl
- example_data/cle_IDT_somatic_exome_template.yaml
This cwl pipeline is to replace current hybrid of alignment_QC wdl and detect_variant toil_cwl implemented in LIMS IDT tumor/normal exome assay.  It will run normal/tumor alignment_QC, tumor/normal concordance check, and variant detection that does NOT include sv detections: manta and cnvkit. Three full tests succeeded (https://jira.ris.wustl.edu/browse/CI-326).
> Add cle_somatic_exome.cwl for CLE IDT somatic exome assay that will be implemented by LIMS

- definitions/pipelines/cle_somatic_exome.cwl
- definitions/pipelines/gathered_cle_somatic_exome.cwl
- example_data/cle_IDT_somatic_exome_template.yaml
With #572 merged, vep_assembly is now required input. Add it to cle_somatic_exome.cwl and gathered_cle_somatic_exome.cwl
> Add vep_assembly as input to cle_somatic_exome

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/exome_alignment.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/subworkflows/varscan_germline.cwl
Specifying an input that does not exist is merely a warning.  Since we have a lot of optional inputs, this means no error is generated when things are mis-wired.
We should work to eliminate warnings from our CWL validation--we can then possibly make Travis CI fail if new warnings are generated.
> Fix some missed connection in workflows and add more secondaryFiles.

- definitions/tools/cellranger_count.cwl
We've just run through a bunch of scRNA seq data with this pipeline, and are seeing memory usages a fair amount below what's being requested:
```
$ gm list analysis_projects.id:e8cad4ecda43457bb9fe9c5cd3b61288/382eb5d530384ed19c7bf3a5070ba3ac/62fe9adcc1ed41b9bd6afd0f065920e5 --show last_succeeded_build.data_directory --nohead | while read i;do perl -nae 'print $1 . "\n" if $_ =~ /job id: (\d+)/' $i/logs/process*.out;done | while read i;do binfo $i | grep memory_bytes;done
memory_bytes       44345270272,
memory_bytes       46636138496,
memory_bytes       43644301312,
memory_bytes       47865040896,
memory_bytes       46829789184,
memory_bytes       44326752256,
memory_bytes       47019626496,
memory_bytes       47343132672,
memory_bytes       47447986176,
memory_bytes       48710610944, …
```
> dropping the mem requirement of cellranger count

- definitions/tools/get_chromosome_list.cwl
If there's a stray extra newline at the end of an interval list, that gets put into the chromosomes list and causes steps like Pindel to choke (when given an empty string for the -c argument)
The underlying fix is really "fix the interval list", but there's no reason not to make this a little more robust as well
> strips trailing empty lines that may cause problems

- definitions/tools/variants_to_table.cwl
In GATK 3.6 "If a VCF record is missing a value, then the tool by
default throws an error, but the special value NA can be emitted instead
if requested at the command line using --allowMissingData."
Depending on the arguments, we might encounter missing values which
would cause an error without this flag.
This behavior was reversed in GATK 4.0 and it will no longer throw an
error on missing values.
> Add --allowMissingData to VariantsToTable

- definitions/pipelines/rnaseq.cwl
- definitions/subworkflows/bam_to_trimmed_fastq_and_hisat_alignments.cwl
- definitions/tools/generate_qc_metrics.cwl
- definitions/tools/hisat2_align.cwl
- definitions/tools/kallisto.cwl
- definitions/tools/stringtie.cwl
Since tools rely on particular values, stop users from accidentallyspecifying the same intent other ways (e.g. "firststrand" instead of "first").  [This change is from a support ticket where that very thing
happened :smile: (XREF: BGAS-651)]
> Make "strand" into an enum in RNA-seq pipeline.

- definitions/subworkflows/cellranger_mkfastq_and_count.cwl
- definitions/tools/cellranger_atac_count.cwl
- definitions/tools/cellranger_count.cwl
- definitions/tools/cellranger_vdj.cwl
The original cellranger CWLs worked great for running samples that had a single instrument data. But when there are multiple instrument data objects there was no easy way to pass them in as a single input directory. I recently learned that you can pass in multiple directory paths separated by a `,` in the `--fastqs` option. Cellranger is able to traverse the different directories and locate the correct fastq files to use. 
By switching to an array of directories we can have the Cellranger pipeline handle getting the correct fastq files instead of setting up the fastq files in the `process_inputs.pl` step or relying on Cromwell to correctly setup multiple directories. 
closes #656
> handle multiple directory inputs

- definitions/tools/filter_vcf_mapq0.cwl
Change described here - fixes an edge case error when all variants already have MQ values.  Tests pass
https://github.com/genome/docker-mapq0-filter/commit/6b5002c5d519bede7eaf546873616e45387a458f
> bumping to v0.2 to fix an edge case error

- definitions/pipelines/cle_somatic_exome.cwl
- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/exome.cwl
- definitions/pipelines/gathered_cle_somatic_exome.cwl
- definitions/pipelines/gathered_somatic_exome.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/pipelines/wgs.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/subworkflows/merge_svs.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/tools/vep.cwl
This is a big one, since it touches anything that uses VEP, which is most workflows. 
We previously assumed that we'd point our tool to a VEP cache, and that it would always be human, and always match the version referred to in the vep tool docker version.  This doesn't work for mouse, or other species, and limits our ability to support multiple projects that may want to anchor themselves to a particular VEP build.
The solution is to expose a bunch of parameters for reference assembly, ensembl version, and species, so that they must be explicitly specified.  While I don't love adding extra complexity to the (already kind of overwhelming) input yamls, asking users to specify the  ensembl version and such seems like a reasonable ask, IMO.
> Support multiple species and builds with VEP

- definitions/tools/mark_duplicates_and_sort.cwl
`cwltool` confuses this for an attempt to insert inline JavaScript.
Closes #684.
> Stop using the ${VAR} syntax in the helper script.

- definitions/tools/filter_vcf_mapq0.cwl
Commit to the script is here.
https://github.com/genome/docker-mapq0-filter/commit/61d8a43004b8a8dad84977301a916f70d84ce230
Has been tested on both human and mouse somatic exome cwls (mouse pr forthcoming)
> handling both unzipped and gzipped vcfs appropriately

- definitions/tools/index_bam.cwl
- definitions/tools/index_cram.cwl
* We previously avoided the `InitialWorkDirRequirement` because a few executors didn't support it.  They generally all do now, so this is better than a manual copy.
* `cwltool` isn't propagating the symlinks, so make a copy of the index instead.  (Other executors end up making a copy later anyway.)  This addresses #691.
> Simplify BAM and CRAM indexers.

- definitions/pipelines/detect_variants_mouse.cwl
- definitions/pipelines/exome_alignment_mouse.cwl
- definitions/pipelines/somatic_exome_mouse.cwl
- definitions/subworkflows/align_sort_markdup.cwl
- definitions/subworkflows/filter_vcf_mouse.cwl
- definitions/subworkflows/mutect.cwl
- definitions/subworkflows/pindel.cwl
- definitions/subworkflows/qc_exome_no_verify_bam.cwl
- definitions/subworkflows/varscan_pre_and_post_processing.cwl
- example_data/alignment_mouse.yaml
- example_data/exome_workflow.tgz.md5
- example_data/somatic_exome_mouse.yaml
This adds a mouse somatic exome workflow. Major changes include:
- adding pipeline-level cwls that remove human specific steps, including:
- removing docm, since no comparable list exists for human
- removing T/N concordance checking, since they will almost always be 100% for inbred mice
- removes bsqr and verify bam id from alignment workflows
- remove gnomad, dbsnp, cosmic, and pon filters
- removing manta and cnvkit for now, since they both have human-specific annotations (we should re-add them or something comparable soon (see issue https://github.com/genome/analysis-workflows/issues/683) 
- adding test data and yamls that allow it to be run (locally, for now)
(P.S. Thanks to @Matthew-Mosior for some contributions)
> Adding Mouse somatic exome workflow

- definitions/tools/collect_wgs_metrics.cwl
This is still the same version of the tool:
```
$ /usr/bin/java -jar /usr/picard/picard.jar CollectWgsMetrics --version
2.18.1-SNAPSHOT
```
Closes #695.
> Use Picard-specific docker image instead of CLE image.

- definitions/pipelines/detect_variants.cwl
Running GATK CombineVariants to merge in the DOCM VCF results in multi-allelic sites. Moving the `decompose` step to after the the `add_docm_variants` should fix this issue.
> Add decompose step after the docm VCF gets merged in

- definitions/subworkflows/align_sort_markdup.cwl
- definitions/tools/mark_duplicates_and_sort.cwl
Since somatic_exome_mouse.cwl doesn't run bqsr, the tumor and normal bams never get renamed, as they do in the human workflow.  This renames them at the markdup step instead
> add output names to prevent file collisions in somatic mouse exome

- definitions/subworkflows/pindel.cwl
- definitions/subworkflows/pindel_cat.cwl
- definitions/tools/cat_all.cwl
- definitions/tools/pindel.cwl
- definitions/tools/split_interval_list_to_bed.cwl
Currently pindel workflow scatters parallel run by chromosomes, which is inefficient and often consumes large memory on big chromosomes. This PR is to change pindel subworkflow scatter by target_region.
Refer to https://jira.ris.wustl.edu/browse/CI-391
> Change pindel subworkflow to scatter by region

- definitions/tools/filter_vcf_depth.cwl
See here for the actual commit: 
https://github.com/genome/docker-depth-filter/commit/c14569ac8d88b4f226a77e975c913bb1f632f81c
using the built-in `add_filter` function correctly removes PASS values when filtering a line (instead of appending the filters and ending up with nonsense like "PASS,DEPTHFILTER"
> bumping to 0.1.2 to remove PASS values when filtering

- definitions/pipelines/rnaseq.cwl
- definitions/tools/generate_qc_metrics.cwl
This fixes the errors outlined in issues https://github.com/genome/analysis-workflows/issues/658 and https://github.com/genome/analysis-workflows/issues/659, related to strandedness settings in QC, and to fastq order in Kallisto
> Fixing strandedness settings in RNAseq pipeline

- definitions/pipelines/cle_aml_trio.cwl
- definitions/pipelines/gathered_cle_aml_trio.cwl
- definitions/tools/bam_readcount.cwl
- definitions/tools/concordance.cwl
- definitions/tools/filter_vcf_docm.cwl
- example_data/cle_aml_trio_template.yaml
This is to replace the legacy aml_trio pipeline that is based on GMS Build-VariantReportingProcess.
Note that the docker image will be "mgibio/bam_readcount_helper-cwl:1.1.0" in bam_readcount.cwl once the PR https://github.com/genome/docker-bam_readcount_helper-cwl/pull/3 is merged.
> Add aml_trio cwl pipeline

- definitions/pipelines/cle_aml_trio.cwl
- definitions/subworkflows/germline_detect_variants.cwl
germline_detect_variants.cwl now includes variants_to_table and add_vep_fields_to_table steps. Update cle_aml_trio.cwl to contain the change. Also add finaLtsv_prefix optional input to handle final_tsv from different sources.
> Update germline_detect_variants step

- definitions/tools/index_bam.cwl
- definitions/tools/index_cram.cwl
We don't ask for them, but `cwltool` sends them along to the output directory if a previous output included them. This change assumes the secondaryFiles are indexes and should be dropped so the main file can be re-indexed.
Closes #697.
> Strip the secondary files from the input file to be indexed.

- definitions/subworkflows/filter_vcf.cwl
- definitions/subworkflows/filter_vcf_mouse.cwl
- definitions/tools/rename.cwl
- definitions/tools/staged_rename.cwl
This closes #733. It mostly supersedes #734.
The Expression tool could've been inline in the workflow, but this will hopefully be more convenient for re-using in other pipelines.
> Add a tool to logically rename a file and use it in our VCF filter subworkflow.

- definitions/tools/cnvnator.cwl
This PR adds the CNVnator cwl as another copy number calling tool for WGS data. This is using the latest released version of `0.4`. This version of CNVnator does have CRAM and BAM support. Originally CNVnator required the reference to be split up in individual chromosome files. With the `0.4` version they now support compressed fasta.gz as a single file input. The issue with using that is that vcf generation perl script does not support a compressed reference input. I decided to generate the individual chromosome reference files when the tool is run. Allowing the CNVnator run and the cnvnator2VCF.pl script to use the same files. 
One issue that I have not been able to find a good solution for is that CNVnator requires the [ROOT](https://root.cern.ch) data analysis framework. In order to …
> adding cnvnator.cwl

- definitions/subworkflows/fp_filter.cwl
- definitions/tools/vcf_sanitize.cwl
This PR implements a "sanitize" step that is needed to remove non-IUPAC reference bases from VCF files. Currently, this occurs when a caller like varscan is run on the GRCh38 reference, which contains 95 positions with non [ACTGN] bases, all from the IUPAC standard (R, Y, S, B, W, etc).  The VCF spec, however, does not allow these bases, and GATK tools (correctly??) choke on them in a VCF.  
GATK-based tools (HaplotypeCaller, Mutect) just skip those non-ACTGN bases, and here, we replicate that behavior by removing any lines from VCFs that contain such a base.
I imagine that we haven't run into this before because this is the first time we're using the varscan-based tumor-only calling pipeline on whole genome data.   
Head of a validation experiment, showing some of the lines that are …
> Sanitize non-ACTGN bases in VCFs

- definitions/tools/annotsv.cwl
this PR adds the cwl tool for running AnnotSV. Decided to create a new branch/pr instead of pushing to #720 
Docker image now contains the AnnotSV files and the `ANNOTSV` env value necessary to run AnnotSV. This cwl does not expose the option to provide your own annotation files. Something that should be added in the future.
Future PR will add this and filtering to single sample sv caller sub workflow.
> adding annotsv.cwl

- definitions/subworkflows/sequence_to_bqsr.cwl
- definitions/tools/sequence_align_and_tag.cwl
- definitions/types/sequence_data.yml
Hot on the heels of #730 is a version that works on either FASTQ or BAM.  This approach saves us from having to maintain two versions of the pipeline and retains the efficiency of piping directly into `bwa` from BAM files.
If this approach looks good, I'll next replace the existing alignment steps in all the workflows and probably remove the existing alignment tool CWLs.
> Introducing `sequence_data` type. Align either FASTQs or BAM!

- definitions/pipelines/cle_aml_trio.cwl
- definitions/pipelines/cle_somatic_exome.cwl
- definitions/pipelines/exome.cwl
- definitions/pipelines/exome_alignment.cwl
- definitions/pipelines/gathered_cle_aml_trio.cwl
- definitions/pipelines/gathered_cle_somatic_exome.cwl
- definitions/pipelines/gathered_somatic_exome.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/wgs.cwl
- definitions/pipelines/wgs_alignment.cwl
- definitions/subworkflows/sequence_align_and_tag_adapter.cwl
- definitions/subworkflows/sequence_to_bqsr.cwl
- definitions/tools/sequence_align_and_tag.cwl
- definitions/tools/sequence_align_and_tag_adapter.cwl
- definitions/types/sequence_data.yml
- example_data/cle_IDT_somatic_exome_template.yaml
- example_data/cle_aml_trio_template.yaml
- example_data/exome_workflow.yaml
- example_data/germline_exome.yaml
- example_data/germline_wgs.yaml
- example_data/somatic_exome.yaml
This is #740 plus an implementation of that concept in the pipelines that include the standard alignment subworkflows.  I had to make an adapter subworkflow because Cromwell was not staging the file inputs when they were pulled as arguments directly leading to errors about files not being found.
I've tested this on the `somatic_exome.yaml` example but not run any full-scale pipelines yet.
> Use new sequence type in alignment.

- .travis.yml
Python 2.7 is EOL at the end of the year, so let's be ready for the future!
> Start testing using Python3 instead.

- definitions/subworkflows/cnvkit_single_sample.cwl
- definitions/tools/cnvkit_vcf_export.cwl
This adds an optional input to the cnvkit vcf caller/exporter to perform filtering(and merging) options provided by cnvkit. The main option I want to use is `cn` which will merge neighboring called segments that have the same copy number. Without this option you could get multiple segments, that should be called a single event, exported as multiple events in the final vcf file. 
During my tests the job would be killed because it would exceed the original 4gb limit. I upped the ram requirement to 8gb and my tests were able to succeed. 
This PR will close issue #752.
> Cnvkit merge segments for vcf export

- definitions/tools/filter_sv_vcf_size.cwl
This adds a cwl tool that allows you to filter svs based on the called size. Deletion calls have a negative number length while duplication calls have a positive number. Using the absolute value function allows you to filter both at the same time. 
I don't expect to use the `max` filter method but it was easy to add and there could be a future use I have yet to think of!
> Add sv size filter

- definitions/tools/filter_sv_vcf_depth.cwl
Second step in closing #761 
Will filter vcfs based on a del/dup depth added by the duphold.cwl in #763 and pass the other sv calls. Currently Manta has other calls with svtype of `BND` and `INS` while Smoove produces calls with `BND` and `INV`
> add duphold depth filtering

- definitions/tools/bcftools_merge.cwl
This cwl tool allows an array of input vcfs to be merged together. input vcfs need to be bgzipped and tabix indexed. merge method `none` produces the best resulting vcf. using the method of `indels` or `both` causes the alternate field to get updated in a way where the variant has `alt1,alt2` which is not ideal for parsing downstream for SVs. The `indels` and `both methods also would only merge 2 calls if the variants have the same starting position and reference. With my testing only a very small number(~400 out of 32k) of variants from multiple callers fit this requirement and were being merged together.
> add bcftools merge cwl tool

- definitions/tools/duphold.cwl
This cwl adds a tool for annotating SVs with [duphold](https://github.com/brentp/duphold). Providing coverage information for called deletions and duplications.
I added the threads option because the tool defaults to 4 threads while we default to 1 thread on the cluster.
First step in closing issue #761
> Add duphold tool

- definitions/tools/pvacbind.cwl
- definitions/tools/pvacfuse.cwl
- definitions/tools/pvacseq.cwl
- definitions/tools/pvacvector.cwl
This version adds AGFusion support to pVACfuse. AGFusion output is a directory, hence we now accept both `File` and `Directory` `type` for the `input_file`. 1.5.0 also adds a new tool, pVACbind, so this PR adds a CWL for it.
> Upgrade to version 1.5.0

- definitions/subworkflows/sequence_to_bqsr.cwl
Cromwell fails to run if the bqsr interval is not provided in the input for alignment workflows.
Cromwell thinks the bqsr interval input is necessary because the sub workflow has it as required even though the above pipeline has it as optional and the tool called has a default value.
> make bqsr interval input optional

- definitions/tools/fastq_align_and_tag.cwl
- definitions/tools/sequence_align_and_tag.cwl
The `-p` option is used for a single interleaved fastq file which gives this warning when aligning with 2 fastq files
```
[W::main_mem] when '-p' is in use, the second query file is ignored.
```
This doesn't cause the alignment step to fail. Downstream steps fail if they require paired end alignments.
The `-P` option should allow the 2 paired end fastq files to be aligned correctly. Manually rerunning this step with `-P` on one of my builds to confirm this works.
> support non interleaved fastqs

- definitions/pipelines/immuno.cwl
- definitions/pipelines/rnaseq.cwl
- definitions/tools/grolar.cwl
- definitions/tools/mutect.cwl
This PR contains 2 small updates meant to fix bugs encountered while testing the workflow with new data. Grolar was updated to generate its output file in the correct location if there is no data for it to parse, and the mutect sample renaming logic was updated to account for tumor/normal pairs where the samples have similar names (in this case, HCC1395 and HCC1395_BL, respectively).
> Immuno workflow bugfixes

- definitions/pipelines/alignment_wgs.cwl
- definitions/pipelines/chipseq.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/tumor_only_wgs.cwl
- definitions/subworkflows/qc_wgs.cwl
The tool is still left in place for now, in case anyone wants to use it for something else.
> Remove bigwig generation from WGS QC process.

- definitions/pipelines/germline_wgs.cwl
- definitions/subworkflows/cnvkit_single_sample.cwl
- definitions/subworkflows/merge_svs.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/subworkflows/sv_depth_caller_filter.cwl
- definitions/subworkflows/sv_paired_read_caller_filter.cwl
- definitions/tools/annotsv_filter.cwl
- definitions/tools/cnvnator.cwl
- definitions/tools/duphold.cwl
- definitions/tools/filter_sv_vcf_read_support.cwl
This changes a few things and ended up being a bigger PR than I expected. 
- cnvkit subworkflow
make default vcf name. previous tumor.nameroot expression does not work unless tumor bam is passed into the tool. Even though the tool itself doesn't use the input.
- remove the quotes around the CHROMOSOMES variable in the cnvnator shell script 
was causing the input chromosomes to be parsed as a single chromosome 'chr1 chr2 chr3 ...' instead of 'chr1' 'chr2' 'chr3' ...
- update duphold docker image version 
previous version had an issue where some manta duplications were not being annotated and then were being filtered out because they had no annotation.
- add bcftools sv merging and annotating with AnnotSV into the merge svs subworkflow
- move depth based sv caller filtering to a subworkflow …
> Sv changes to wgs pipeline

- definitions/tools/cellranger_feature_barcoding.cwl
This PR adds cwl to run feature barcoding samples. 
Little different setup compared to other cellranger pipelines because you have to provide a `libraries.csv` input. This describes the location, name, and type of each fastq used. The bash script generates this for each Cromwell run as the path of the fastqs isn't known till they're transferred to the inputs directory. 
Am required to pass in the sample names(and in our system it's actually library names) for both antibody and expression samples. This is because cellranger is picky about the naming of their fastq files. 
For example if the input directory looked like this:
```
SAMPLE1-lib1_S1_L002_R1_001.fastq.gz
SAMPLE1-lib1_S1_L002_R2_001.fastq.gz
SAMPLE1-lib1_S1_L002_I1_001.fastq.gz
```
and you had the sample name input as `SAMPLE1` …
> adding cellranger feature barcoding support

- definitions/pipelines/detect_variants.cwl
Since scatter_count is a required input to the mutect subworkflow, it needs to either be a required input here or have a default value.  I chose the latter and set a default scatter of 50, which is what we provide upstream in the exome workflow anyway
> adding default scatter count for mutect

- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/aml_trio_cle_gathered.cwl
- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_cle.cwl
- definitions/pipelines/somatic_exome_cle_gathered.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/pipelines/tumor_only_exome.cwl
- definitions/pipelines/tumor_only_wgs.cwl
- definitions/subworkflows/filter_vcf.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/tools/filter_vcf_custom_allele_freq.cwl
- definitions/tools/vep.cwl
- definitions/types/vep_custom_annotation.yml
- example_data/cle_aml_trio_template.yaml
- example_data/detect_variants/detect_variants.yaml
- example_data/detect_variants/vep.yaml
- example_data/exome_workflow.yaml
- example_data/germline_exome.yaml
- example_data/germline_wgs.yaml
- example_data/somatic_exome.yaml
- example_data/somatic_wgs.yaml
This adds a new vep custom annotation type. Plan is to have this replace the individual inputs used with clinvar and gnomad vcfs and provide more customization to the pipelines. So when new versions of databases come out we can quickly add them to the pipelines.
I have gotten the `tumor_only_detect_variants.cwl` pipeline, which includes VEP annotation and gnomad filtering, to successfully complete. 
- To support the other file types I had to add the `.filter(String)` in the javascript parsing to remove the trailing comma.(non vcf input files do not have vcf fields as inputs!)
- for the somatic pipelines that do gnomad filtering, this assumes that you are adding the `AF` field and setting the gnomde_filtering field as true. and will then be filtering based on the `${annotation_name}_AF` …
> Parameterize custom vep annotations with custom type

- definitions/pipelines/germline_wgs.cwl
In a previous PR I duplicated the output link for 2 files. 
This caused one of the outputs be incorrect and for there to be 2 outputs of the same file in the outputs.json. When the GMS attempted to move the results it fails as there are 2 files with the same name. 
This PR correctly links the survivor TSV output file.
> link correct output file

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/subworkflows/filter_vcf.cwl
- definitions/tools/filter_cle_variants.cwl
- definitions/tools/filter_known_variants.cwl
This PR adds a new tool, `filter_cle_variants`. It takes in an input target vcf and a second vcf containing CLE validated variants, and adds a "CLE" tag to the INFO field of variants in the target file that are present in the CLE file. 
This is intended for the immuno workflow, but was added to the `filter_vcf` subworkflow, which is shared by many pipelines. The input vcf is already present in all other calling pipelines, and the CLE vcf is optional. When the CLE vcf is not provided, this step does nothing beyond renaming the input file and adding the line `##FILTER=<ID=PASS,Description="All filters passed">`, so it shouldn't effect the other pipelines. 
Note that the input vcf to this step must have an index file; due to this, I added in a `secondaryFiles` requirement to the `filter_vcf` …
> Added cle variant filter

- definitions/tools/name_sort.cwl
Increase LSF RAM to 26GB for sambamba name sort.
> Sambamba RAM for name sort

- .travis.yml
- README.md
This should only run the docs generation step when a PR is merged. Need to generate and add an application token with access to the wiki repo to the travis environment. Will do that next.
> initial attempt at travis yml for docs generation

- definitions/subworkflows/align_sort_markdup.cwl
- definitions/subworkflows/bam_to_bqsr.cwl
- definitions/subworkflows/bisulfite_qc.cwl
- definitions/subworkflows/cnvkit_single_sample.cwl
- definitions/subworkflows/cram_to_cnvkit.cwl
- definitions/subworkflows/fastq_to_bqsr.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/subworkflows/germline_filter_vcf.cwl
- definitions/subworkflows/mutect.cwl
- definitions/subworkflows/phase_vcf.cwl
- definitions/subworkflows/pindel.cwl
- definitions/subworkflows/qc_exome.cwl
- definitions/subworkflows/qc_exome_no_verify_bam.cwl
- definitions/subworkflows/qc_wgs.cwl
- definitions/subworkflows/qc_wgs_mouse.cwl
- definitions/subworkflows/sequence_to_bqsr.cwl
- definitions/subworkflows/sequence_to_bqsr_mouse.cwl
- definitions/subworkflows/varscan_pre_and_post_processing.cwl
- definitions/tools/clip_overlap.cwl
This fixes some validator warnings in our subworkflows that result from one of a few circumstances:
* an optional input with default is mapped to a required input:
this is made required to eliminate the ability to pass `null` overriding the default
* some missing `secondaryFile` declarations have been added.
> Fixing warnings: subworkflow directory low-hanging fruit edition

- definitions/tools/mark_duplicates_and_sort.val_test01.yaml
This yaml is not needed and doesn't belong here.  It is missed in https://github.com/genome/analysis-workflows/pull/822
> Hackathon_120319_remove

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_mouse.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_exome_mouse.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/pipelines/tumor_only_exome.cwl
- definitions/pipelines/tumor_only_wgs.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/tools/vep.cwl
Following discussion in #774 and some testing, it was determined that the vep configuration used in our pipeline does not use a `.index` file; it has the `faidx` module and so is able to generate/use a `.fai` file. Even if our pipeline is modified to use a different vep docker image or a local install that is configured to require this file, vep will generate it on the fly if not present. Additionally, our workflow runner (Cromwell) does not support optional `secondaryFiles`, so this requirement will be removed completely. This also closes #830, since there is no need to provide an example file.
> Remove outdated secondaryFile

- definitions/tools/bam_to_fastq.cwl
- definitions/tools/generate_qc_metrics.cwl
- definitions/tools/hisat2_align.cwl
- definitions/tools/kallisto.cwl
- definitions/tools/stringtie.cwl
- definitions/tools/transcript_to_gene.cwl
removes the latest image tags for the cwl tools. future images and PRs should be made to use smaller images instead of the large rnaseq one. 
WIP until the docker image creation succeeds on docker hub
> use a docker image tag for rnaseq tools

- definitions/tools/cnvnator.cwl
This makes some changes to address issues #838 and #839. Specifically:
* avoids the `${}` syntax
* pulls `thisroot.sh` into the inline bash script so we're assured to be running under `/bin/bash`
I ran this with a tiny test.  it completed, but I'd feel better using a test case that produces meaningful results.
> Address some compatibility issues with cnvnator.cwl

- definitions/pipelines/alignment_wgs_mouse.cwl
- definitions/pipelines/chipseq.cwl
- definitions/pipelines/chipseq_alignment_mouse.cwl
- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_mouse.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
This mostly makes optional inputs with defaults into required inputs with defaults.  This should have no practical effect except to make `cwltool --validate` stop warning as much.
For good measure, this PR also includes one change where an optional input really should've been required--see, attacking warnings is worthwhile :smile:
> Reduce pipeline warnings

- definitions/pipelines/immuno.cwl
- definitions/tools/hla_consensus.cwl
This PR adds a tool for finding a consensus between optitype HLA calls and clinical calls (when available) and adds it to the immuno pipeline. The tool's basic logic has been reviewed by @susannasiebert, along with verification that some test cases (see [repo](https://github.com/johnegarza/consensus-script-draft)) pass and agree with the consensus rules we discussed several weeks ago. Once this PR is merged in, the immuno pipeline will be ready for its first stable release.
> Add HLA type consensus tool to immuno wf

- definitions/subworkflows/downsampled_alignment.cwl
- definitions/tools/downsample.cwl
Picard currently forces BAM output even given CRAM input, so this assumes BAM output for now.
We can revisit that if this line is changed in the future:
https://github.com/broadinstitute/picard/blob/d7e09b8e3f7f0583346117b95aafb7bd815aaa65/src/main/java/picard/sam/DownsampleSam.java#L215
> Expose more options in the downsample tool.

- definitions/subworkflows/pindel.cwl
This input was accidentally left out, forcing the tool to use its default and creating a mismatch with the expected sample name in the rest of the pipeline. Patched in a processing profile used in the first gms test run, fixing the error that was preventing this build from succeeding.
> Missed input connection, already fixed in gms test run

- definitions/subworkflows/cram_to_bam_and_index.cwl
- definitions/subworkflows/vcf_eval_cle_gold.cwl
- definitions/subworkflows/vcf_eval_concordance.cwl
- definitions/tools/combine_variants_concordance.cwl
- definitions/tools/cram_to_bam.cwl
- definitions/tools/eval_cle_gold.cwl
- definitions/tools/eval_vaf_report.cwl
- definitions/tools/select_variants.cwl
- definitions/tools/sompy.cwl
For CLE, there are bunch of old evaluation scripts to process evaluation analysis of vcf concordance and gold standard outputs for sensitivity, specificity and positive predict value (PPV). This PR is to replace those outdated scripts with cwl workflows that use som.py (bcftools inside) as comparison tool and vaf_report process to evaluate the result. Two subworkflows are tested and the result matches expectation.
Refer to https://jira.ris.wustl.edu/browse/CI-421
> Add workflows to process CLE vcf evaluation analysis

- definitions/pipelines/immuno.cwl
- definitions/subworkflows/pvacseq.cwl
- definitions/tools/vep.cwl
Previously, there were 2 pairs of output files with the same name.
`annotated.vcf_summary.html` was a hardcoded name in vep, run in both the `somatic_exome` and `germline_exome` pipeline. This now pulls part of its name from the input vcf.
`variants.annotated.tsv` had an optional unused prefix in add_vep_fields_to_table, run in both `somatic_exome` and `pvacseq`. I added a new input with a default that adds a prefix to the pvacseq branch. Neither change requires any new inputs.
> Minimal changes to ensure unique immuno output names

- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/tools/optitype_dna.cwl
Previously, cram to bam conversion was being performed by samtools without a reference fasta explicitly provided. Samtools is smart enough to check the cram header for a path to the reference and try using that. This works on compute0 since the entire filesystem is mounted by default, but not on compute1, which is closer to a standard docker implementation and only mounts explicitly defined volumes. This PR adds the reference as an input, allowing Cromwell to handle staging if the reference is specified as a file. If it is a string, the user must ensure that dir containing the reference (and the index) is properly mounted by the optitype docker container.
> Explicitly pass reference for portable cram decompression

- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/aml_trio_cle_gathered.cwl
- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_mouse.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_cle.cwl
- definitions/pipelines/somatic_exome_cle_gathered.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_exome_mouse.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/pipelines/tumor_only_exome.cwl
- definitions/pipelines/tumor_only_wgs.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/tools/vep.cwl
This is a follow up to #774, and should address issue #832. Internally, both the reference fasta and vep cache are located in a central directory that Cromwell is configured to mount in each step's docker container, so they are always accessible. Passing the cache directory as a string prevents Cromwell from staging it into the working directory and saves space. However, adding in the option to specify this as a Directory type allows for more portable workflows; notably, example yamls can now exclusively use relative paths, allowing us to package them alongside example data for easy distribution and usage.
> More input choices to make vep_cache more portable

- definitions/tools/merge_vcf.cwl
bcftools is installed in the same location. using the same version of bcftools found in the cle v1.3.1 image. 
Could update to bcftools version 1.9 but decided to keep it the same version
> slim bcftools image

- definitions/tools/combine_variants_wgs.cwl
* removes commented out input 
* uses small gatk 3.6.0 image
cle image has version `3.6-0-gf185a75` while the gatk image has `3.6-0-g89b7209` (found using `/usr/bin/java -jar /opt/GenomeAnalysisTK.jar --version` in both images)
is this an issue?
> Slim image combine variants wgs.cwl

- definitions/tools/set_filter_status.cwl
small gatk image. continue using the gatk 3.6 version. 
basically the same as #857
> use small gatk image

- definitions/tools/remove_end_tags.cwl
using the small bcftools version 1.3.1 image for `remove_end_tags.cwl` tool
similar to #856
> use small bcftools image for remove_end_tags.cwl

- definitions/tools/collect_gc_bias_metrics.cwl
cle image 1.3.1 has picard version `2.18.1-SNAPSHOT`
picard-cwl:2.18.1 has version `2.18.1-SNAPSHOT` installed in the same location
(`/usr/bin/java -jar /usr/picard/picard.jar CollectGcBiasMetrics --version`)
> use small picard 2.18.1 image collect_gc_bias_metrics.cwl

- definitions/tools/position_sort.cwl
cle image `1.3.1` uses sambamba version `0.6.4`
`mgibio/sambamba-cwl:0.6.4` has sambamba version `0.6.4` installed in the same location
(`/usr/bin/sambamba --version`)
> use small sambamba image for position_sort.cwl

- definitions/tools/combine_variants.cwl
cle 1.3.1 has gatk `3.6-0-gf185a75`
gatk-cwl:3.6.0 has `3.6-0-g89b7209`
similar to #857 and other linked PRs
> use small gatk3.6 image combine_variants.cwl

- definitions/tools/docm_add_variants.cwl
cle image version `1.4.2` uses gatk version `3.6-0-gf185a75` which is the same gatk version found in cle image version `1.3.1`
using gatk-cwl:3.6.0 which is version `3.6-0-g89b7209`
similar to #857 and others
> use small gatk 3.6 image for docm_add_variants.cwl

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/subworkflows/bam_to_trimmed_fastq_and_hisat_alignments.cwl
- definitions/subworkflows/fp_filter.cwl
- definitions/subworkflows/gatk_haplotypecaller_iterator.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/subworkflows/qc_exome_no_verify_bam.cwl
- definitions/tools/add_string_at_line.cwl
- definitions/tools/add_string_at_line_bgzipped.cwl
- definitions/tools/collect_hs_metrics.cwl
- definitions/tools/filter_known_variants.cwl
- definitions/tools/filter_vcf_custom_allele_freq.cwl
- definitions/tools/filter_vcf_docm.cwl
- definitions/tools/filter_vcf_exac.cwl
- definitions/tools/generate_qc_metrics.cwl
- definitions/tools/hisat2_align.cwl
- definitions/tools/index_vcf.cwl
- definitions/tools/kallisto.cwl
- definitions/tools/stringtie.cwl
- definitions/tools/survivor.cwl
- definitions/tools/varscan_process_somatic.cwl
According to the [CWL specification](https://www.commonwl.org/v1.0/Workflow.html#StepInputExpressionRequirement), `StepInputExpressionRequirement` must be defined in order to use the `valueFrom` field in inputs. Cromwell isn't very strict about some CWL requirements, including this one, but other runners are, as noted in #831. I've updated all instances of the missing requirement I could find.
> Added missing requirements to improve cwl portability

- definitions/tools/filter_vcf_coding_variant.cwl
- definitions/tools/filter_vcf_custom_allele_freq.cwl
By default, VEP attempts to use a cache version corresponding to VEP's version. `mgibio/vep_helper-cwl:1.0.0` contains VEP v93, while `mgibio/vep_helper-cwl:1.1.0` contains VEP v95. Our main VEP tool, `tools/vep.cwl`, was updated to version 95 some time ago, but `tools/filter_vcf_coding_variant.cwl` and `tools/filter_vcf_custom_allele_freq.cwl` were not. This means any pipeline using both `tools/vep.cwl` and one of the two above was using different VEP caches at different steps; I'm not sure what effect this will have had. `vep.cwl` is already explicitly using VEP's `--cache_version` option; we may want to add it to these 2 tools as well.
> Globally update VEP version from 93 to 95 for consistency

- definitions/subworkflows/vcf_eval_cle_gold.cwl
- definitions/subworkflows/vcf_eval_concordance.cwl
Input VCFs (gold vcf, query vcf, base vcf) need to be restricted with ROI bed first before further process. This change is tested ok with real data in https://jira.ris.wustl.edu/browse/CI-433. Also refer to https://jira.ris.wustl.edu/browse/CI-421 for workflow development.
> Restrict input VCFs with ROI bed first

- definitions/pipelines/immuno.cwl
- definitions/tools/hla_consensus.cwl
MHC class I alleles follow a standard nomenclature, but not all class II alleles follow it. This, in addition to the notation used for uncertain clinical calls and paired class II alleles, makes parsing a single input difficult. Breaking up the input into class I and class II allows most of the current parsing script to remain usable, while eliminating most of the edge cases caused by class II alleles.
> Better handling of MHC Class II alleles

- definitions/pipelines/immuno.cwl
- definitions/subworkflows/pvacseq.cwl
- definitions/tools/pvacseq.cwl
Current GMS immuno builds are failing because pvacseq outputs 3 sets of 3 files, where each set contains files with identical names. Pvacseq outputs these into 3 subdirectories, but the cwl extracts each file individually, causing naming collisions. Renaming the files could work, as described in the "Rename an output file" section [here](https://www.commonwl.org/user_guide/misc/); however, Cromwell does not support this option. In order to avoid sending each of these 9 files to a tool just to rename, I opted to instead just grab each of the 3 output directories. They do include some additional temp and log files, but they aren't very large and can easily be cleaned up later.
> ensure unique output names to prevent gms staging failures

- definitions/tools/vcf_sanitize.cwl
Closes #895 by adding in the missing requirement and using the `===` seen elsewhere in our code instead of `.equals` (which my browser tells me is not a function on strings :smile:).
> VCF Sanitize: JS fixes

- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/subworkflows/cnvkit_single_sample.cwl
- definitions/subworkflows/cram_to_cnvkit.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/subworkflows/sv_depth_caller_filter.cwl
- definitions/subworkflows/sv_paired_read_caller_filter.cwl
- definitions/tools/annotsv.cwl
- definitions/tools/cnvkit_batch.cwl
- definitions/tools/cnvnator.cwl
- definitions/tools/duphold.cwl
- example_data/germline_wgs.yaml
This PR has multiple updates:
* updates cnvkit to default to flat reference
this allows the SV callers to run without providing a `reference.cnn` input (#726)
* adds cnvkit input `target_average_size `
I have not linked this in with the pipeline. 
* makes the cnvkit `method` input an enum
* remove default method for cnvkit single sample
the cnvkit batch tool already has the `hybrid` default
* make `wgs` default method for cnvkit in wgs pipeline
* add some cnvkit input doc lines at the tool level
* update AnnotSV tool to use full path
* update some reference inputs in sv tools to allow `File` or `string`
* updated example `germline_wgs.yaml`
the exome bams used previously cannot succeed in Smoove (#837)
the somatic wgs example yaml references …
> CNVkit and other SV updates

- definitions/pipelines/detect_variants_mouse.cwl
@johnegarza and @susannasiebert helped me sort this out.  The mouse detect variants pipeline was not working due to changes elsewhere. This fix allows me to get complete builds. 
Before this fix I was getting errors like this
```
File "bam_readcount_helper.py", line 52, in <module>
sample_index = vcf_file.samples.index(sample)
ValueError: 'TUMOR' is not in list
Traceback (most recent call last):
File "bam_readcount_helper.py", line 52, in <module>
sample_index = vcf_file.samples.index(sample)
ValueError: 'TUMOR' is not in list
ln: failed to access '/cromwell-executions/somatic_exome_mouse.cwl/4620f4e7-d06a-4d23-a695-5c21e5ed7555/call-detect_variants/detect_variants_mouse.cwl/520d5353-a6f8-4c07-ba14-6670b72c2d01/call-tumor_bam_readcount/execution/cwl.output.json': No such file or directory …
```
> used sample names instead of generic tumor and normal

- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/subworkflows/germline_detect_variants.cwl
this closes #906 
CWLs to potentially update:
```
definitions/pipelines/aml_trio_cle.cwl:        run: ../subworkflows/germline_detect_variants.cwl
definitions/pipelines/germline_exome.cwl:        run: ../subworkflows/germline_detect_variants.cwl
definitions/pipelines/germline_wgs.cwl:        run: ../subworkflows/germline_detect_variants.cwl
definitions/pipelines/germline_exome_hla_typing.cwl:        run: germline_exome.cwl
definitions/pipelines/aml_trio_cle_gathered.cwl:        run: aml_trio_cle.cwl
definitions/pipelines/immuno.cwl:        run: germline_exome_hla_typing.cwl
```
@dufeiyu let me know the aml pipeline does not need to change.
> add raw vcf to outputs for germline pipelines

- definitions/pipelines/alignment_exome.cwl
- definitions/pipelines/alignment_wgs.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/pipelines/tumor_only_exome.cwl
- definitions/pipelines/tumor_only_wgs.cwl
- definitions/subworkflows/sequence_align_and_tag_adapter.cwl
- definitions/subworkflows/sequence_to_bqsr.cwl
- definitions/tools/sequence_align_and_tag.cwl
- definitions/types/trimming_options.yml
In this version only two options are exposed.  I suspect it'd be good to support all the options seen in the RNA version of trimming (and possibly to harmonize the two approaches to passing trimming parameters!) in order to add this to `immuno.cwl` as well:
https://github.com/genome/analysis-workflows/blob/700e73aaed6db1ad538dd27b2e1709f436ad3edb/definitions/pipelines/immuno.cwl#L32-L41
I thought it better to introduce this first and then tackle that as a separate step.
This is part of genome/covid-19#8 and should support the options currently required by that issue.
> Add Flexbar to Sequence Alignment Step

- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_mouse.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_cle.cwl
- definitions/pipelines/somatic_exome_cle_gathered.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_exome_mouse.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/pipelines/tumor_only_exome.cwl
- definitions/pipelines/tumor_only_wgs.cwl
Closes #915
Removes requirement of a second interval list from somatic workflows, and instead bases the roi for variant calling on the target region plus some padding (configurable option)
> Add padding to target regions in somatic variant calling workflows

- definitions/pipelines/germline_exome_gvcf.cwl
replaces #917 
This PR adds a cwl pipeline for exome GVCF generation which can be used for downstream joint genotyping.
> add germline_exome_gvcf.cwl with trimming options

- definitions/pipelines/germline_wgs_gvcf.cwl
very similar to #917 but for wgs. Will allow users to get aligned crams and GVCF files which can be used for downstream joint genotyping analysis.
> adding germline_wgs_gvcf pipeline

- definitions/tools/sequence_align_and_tag.cwl
cwltool wants the $ to be escaped but Cromwell doesn't, so it's impossible to make one version that works with both tools.
> Trimming: avoid using ${...} syntax in our shell script.

- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/aml_trio_cle_gathered.cwl
- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_nonhuman.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_cle.cwl
- definitions/pipelines/somatic_exome_cle_gathered.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_exome_nonhuman.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/subworkflows/varscan_pre_and_post_processing.cwl
- definitions/tools/picard_merge_vcfs.cwl
- example_data/cle_IDT_exome_template.yml
- example_data/cle_IDT_somatic_exome_template.yaml
- example_data/cle_aml_trio_template.yaml
- example_data/detect_variants/detect_variants.yaml
- example_data/detect_variants/detect_variants_chr22.yaml
- example_data/somatic_exome.yaml
- example_data/somatic_exome_mouse.yaml
- example_data/somatic_wgs.yaml
* Upgrades Picard Merge VCFs to the version in GATK 4.1.8.1.
* Exposes a generic scatter parameter for all variant detectors.
* Scatters Varscan by region like other detectors.
Closes #921.
> Support Scattering in Varscan, too

- definitions/tools/sort_vcf.cwl
#963 switched Picard docker images from an mgibio maintained image to the official Broad image. The mgibio image included the Picard jar in two different locations, but it's only present in one in the Broad image. This patch updates the path to the one present in the Broad image; all other Picard cwls use the path present in both images.
> Updating tool path to work in new docker image

- definitions/pipelines/germline_wgs.cwl
- definitions/subworkflows/merge_svs.cwl
- definitions/subworkflows/single_sample_sv_callers.cwl
- definitions/tools/filter_sv_vcf_blocklist_bedpe.cwl
An extra step to filter SVs listed in blocklist bedpe is needed for germline_wgs.cwl.  Refer to https://jira.ris.wustl.edu/browse/CI-487 and https://github.com/genome/analysis-workflows/issues/943
> Add SV blocklist vcf filter

- definitions/subworkflows/joint_genotype.cwl
- definitions/tools/combine_gvcfs.cwl
- definitions/tools/gatk_genotypegvcfs.cwl
this workflow allows users to joint genotype multiple samples at once
* takes in array of GVCF files(from multiple samples)
* merges into a single GVCF file
* scatter by `intervals` input to genotype just that region from the single large GVCF file
* merges genotyped vcfs
* annotates, filters,tsv generation similar to the `germline_detect_variants.cwl` subworkflow
> adding joint genotype subworkflow

- definitions/tools/smoove.cwl
This PR upgrades smoove to version `0.2.6`. The previous version was `0.1.6`. I decided to not use the sha256 for better readability on what version is being used in the CWL. 
There are a lot of improvements in calling variants, speeding up analysis, and bug fixes.
The location of where smoove is installed has changed. The inputs/outputs are the same.
part of #948
> Smoove to v0.2.6

- definitions/tools/cellranger_count.cwl
- definitions/tools/cellranger_feature_barcoding.cwl
- definitions/tools/cellranger_mkfastq.cwl
- definitions/tools/cellranger_vdj.cwl
I was able to run a small test dataset through the mkfastq and count steps. 
I downloaded the example bcl data from  
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/mkfastq#example_data
```
bcl_directory:
class: Directory
path: /data/cellranger-tiny-bcl-1.2.0
simple_sample_csv:
class: File
path: /data/cellranger-tiny-bcl-simple-1.2.0.csv
sample_name: test_sample
reference:
class: Directory
path: /gscmnt/gc2560/core/reference_sequences/refdata-cellranger-GRCh38-3.0.0
chemistry: SC3Pv2
```
> upgrade cellranger to version 4.0.0

- definitions/tools/kallisto.cwl
produces no changes to gene/transcript abundance on our test data, and the only difference in the fusion outputs is some minor changes to ordering of lines in the files.  Should be a seamless upgrade
> updating kallisto version

- definitions/tools/call_duplex_consensus.cwl
- definitions/tools/call_molecular_consensus.cwl
- definitions/tools/clip_overlap.cwl
- definitions/tools/duplex_seq_metrics.cwl
- definitions/tools/extract_umis.cwl
- definitions/tools/filter_consensus.cwl
- definitions/tools/group_reads.cwl
This switches away from our fat DNA alignment image to an fgbio image on biocontainers as well.
This is part of #948.
> Upgrade fgbio to 1.3.0

- definitions/pipelines/alignment_exome_nonhuman.cwl
- definitions/pipelines/somatic_exome_nonhuman.cwl
Added bam/fastq input compatibility for alignment_exome_nonhuman.cwl pipeline. This was done using sequence_to_bqsr_nonhuman.cwl. The is name is misleading as bqsr is not actually ran for this subworkflow.
> Added bam/fastq input compatability for alignment_exome_nonhuman.cwl

- definitions/pipelines/alignment_umi_duplex.cwl
- definitions/pipelines/alignment_umi_molecular.cwl
- definitions/tools/sequence_to_bam.cwl
The UMI pipelines depend on having BAMs for input, but previously our outer pipeline CWLs required FASTQ inputs which were then immediately converted to BAM.  Now if a BAM is available it can be used as an input to avoid this conversion step.
Closes #969 in spirit.
> Convert UMI alignment pipelines to use `sequence_data` custom type.

- definitions/pipelines/alignment_exome.cwl
- definitions/pipelines/alignment_exome_nonhuman.cwl
- definitions/pipelines/alignment_umi_duplex.cwl
- definitions/pipelines/alignment_umi_molecular.cwl
- definitions/pipelines/alignment_wgs.cwl
- definitions/pipelines/alignment_wgs_nonhuman.cwl
- definitions/pipelines/aml_trio_cle.cwl
- definitions/pipelines/aml_trio_cle_gathered.cwl
- definitions/pipelines/chipseq.cwl
- definitions/pipelines/chipseq_alignment_nonhuman.cwl
- definitions/pipelines/germline_exome.cwl
- definitions/pipelines/germline_exome_gvcf.cwl
- definitions/pipelines/germline_exome_hla_typing.cwl
- definitions/pipelines/germline_wgs.cwl
- definitions/pipelines/germline_wgs_gvcf.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_cle.cwl
- definitions/pipelines/somatic_exome_cle_gathered.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_exome_nonhuman.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/pipelines/tumor_only_exome.cwl
- definitions/pipelines/tumor_only_wgs.cwl
This cleans up the documentation for "sequence" inputs (#987) and then propagates the updated documentation to other pipeline CWLs that have sequence inputs.  Also fixes a few typos and redundancies in other somatic documentation.
> Documentation updates (mostly to "sequence" input fields)

- definitions/pipelines/rnaseq.cwl
- definitions/pipelines/rnaseq_star_fusion.cwl
- definitions/pipelines/rnaseq_star_fusion_with_xenosplit.cwl
- definitions/tools/stringtie.cwl
I think there is a small bug in the new rnaseq_star_fusion workflow, the bigwig step is looking for an indexed bam file but no indexed file is getting passed. this results in cwl errors such as this:
{code}
Could not localize /storage1/fs1/obigriffith/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-mark_dup/execution/MarkedSorted.bai -> /storage1/fs1/obigriffi
th/Active/gmsroot/model_data/35693d91d68a42d292998a5dd3789c4a/build1aeba2dfb53e4ef592d91c13a231a78a/tmp/cromwell-executions/rnaseq_star_fusion.cwl/24d995d7-a045-4d96-9217-399c3e11ec86/call-cgpbigwig_bamcoverage/inputs/-1277726306/MarkedSorted.bai: …
> fixed bug regarding missing indexed bam in bigwig

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/somatic_exome.cwl
- definitions/pipelines/somatic_exome_gathered.cwl
- definitions/pipelines/somatic_wgs.cwl
- definitions/subworkflows/filter_vcf.cwl
- definitions/tools/filter_known_variants.cwl
- definitions/tools/intersect_known_variants.cwl
This PR is a fix for #979. 
First, it updates the annotation step of the workflow: previously, any variant present in the cle vcf (if provided) matching a variant in the pipeline vcf was annotated in the pipeline vcf; now, only passing variants in the cle vcf are considered. The annotation label was updated from `PREVIOUSLY_DISCOVERED` to `CLE_VALIDATED` to more clearly indicate the source of the annotation, and the name of the input file variable within the workflows was updated accordingly. The behavior in the event that no cle vcf is provided remains unchanged: the input vcf is simply copied to be passed along to the next step unchanged.
Next, it adds an intersection step just before pvacseq is run. If a cle vcf is provided, this step takes the intersection of passing cle variants and …
> Limit pvacseq input to passing cle and pipeline variants

- definitions/tools/merge_bams.cwl
I don't love that this requires specifying it twice (in the cwl and the call to picard, but any other way gets janky kind of fast
> Handling picard memory in the merge step

- definitions/pipelines/detect_variants.cwl
- definitions/pipelines/detect_variants_nonhuman.cwl
- definitions/pipelines/detect_variants_wgs.cwl
- definitions/pipelines/immuno.cwl
- definitions/pipelines/tumor_only_detect_variants.cwl
- definitions/subworkflows/germline_detect_variants.cwl
- definitions/subworkflows/joint_genotype.cwl
- definitions/subworkflows/pvacseq.cwl
- definitions/tools/pvacbind.cwl
- definitions/tools/pvacfuse.cwl
- definitions/tools/pvacseq.cwl
- definitions/tools/pvacvector.cwl
- definitions/tools/vep.cwl
This involved quite a few changes to the inputs since those changed in the new version. The VEP version was also updated to one that has the new Frameshift plugin, which is required for running pVACseq 2.0.
@johnegarza if you could have a look at the immuno.cwl to make sure I didn't miss anything, that would be great.
> Update pvactools CWLs to version 2.0.0

- definitions/pipelines/rnaseq.cwl
**Background**:
There is a broken step in `definitions/pipelines/rnaseq.cwl` because it tries to index an unsorted BAM. For fixing this problem, a new step was added in order to sort a merged BAMs between the `merge` and `index_bam` step in rnaseq.cwl.
**Changes**:
There is a built-in cwl tool `definitions/tools/position_sort.cwl` for this purpose. I added it in rnaseq.cwl, and I changed inputs in the `index_bam` and `mark_up` step accordingly.
> Fix the problem of indexing an unsorted merged BAM in rnaseq.cwl

- definitions/tools/bam_to_bigwig.cwl
- example_data/rnaseq/workflow.yaml
This PR has two updates. I finally confirmed that the current rnaseq.cwl is now working with these updates.
(1) Fix `definitions/tools/bam_to_bigwig.cwl` as a subsequent update of #1007
The current rnaseq.cwl was broken in the `cgpbigwig_bamcoverage` step, because of invalid `MarkedSorted.bai` requirement. This PR fixes this broken step.
(2) Update rnaseq.cwl workflow example for the issue #958 
The previous workflow example was outdated. I updated the inputs YAML file, and I confirmed that this workflow example for `rnaseq.cwl` is perfectly working now.
> Fix cgpbigwig_bamcoverage step and update workflow example of rnaseq.cwl

- definitions/pipelines/rnaseq_star_fusion.cwl
- definitions/tools/stringtie.cwl
- example_data/rnaseq/workflow_star_fusion.yaml
Updated version of stringtie from version 1.3.3 to 2.1.4.
Coverage,FPKM and TPM values do change in the stringtie_gene_expression.tsv output file for version 2.1.4 compared to version 1.3.3 but the workflow finishes successfully!
> Updated stringtie version to 2.1.4

- definitions/tools/strandedness_check.cwl
> Switch to docker image hosted in our mgibio namespace.

- example_data/somatic_exome.yaml
To match the type in pipelines/somatic_exome.cwl, this should be an array of `File` rather than of strings.
https://github.com/genome/analysis-workflows/blob/389f6edccab082d947bee9c032f59dbdf9f7c325/definitions/pipelines/somatic_exome.cwl#L69-L70
> Example YAML: bqsr_known_sites is an array of Files.

- definitions/tools/mutect.cwl
The previous regex fails when there are lines in the bam header like this, which contain the SM tag as well as trailing information, all of which gets captured. 
`@PG     ID:bwa.2        PN:bwa  VN:0.7.12-r1039 CL:bwa mem -t 8 -T 0 -R @RG\tCN:BI\tDT:2010-03-12T00\tID:61D5N.8\tLB:Solexa-21878\tPL:illumina\tPU:61D5NAAXX100312.8\tSM:TCGA-AB-2821-03B-01W-0728-08 /alignment/reference/GRCh38.d1.vd1.fa /alignment/scratch1yVgmO/fastq/rmdup/61D5N.8_1.fq.gz /alignment/scratch1yVgmO/fastq/rmdup/61D5N.8_2.fq.gz`
This change restricts to looking at `@RG` lines and only captures the sample name. 
It will fail on sample names with spaces in them, but [a space in a filename is a space in one's soul](https://twitter.com/aaronquinlan/status/711593127551733761). (and I'm fairly confident that there are …
> update mutect regex to better handle sample name extraction

- definitions/subworkflows/sequence_to_bqsr_nonhuman.cwl
This PR resolves two issues for the non human somatic exome
1. resolves improper merging with multiple instrument data, see #998 
2. There was an issue where QC metric output files were named the same for tumor and normal resulting from the input bams having the same name (MarkedSorted.bam). This caused the GMS builds to fail as the GMS would try and copy the same named output for 2 different results. 
Workflow has been tested and is known to work, see buildID: 2feba7f0981e4b8cbb45951d72173291
> changes to get non_human somatic exome to work

- definitions/tools/filter_vcf_docm.cwl
- definitions/tools/mutect.cwl
somatic_exome workflow was breaking with an error indicating that the sample name wasn't being extracted from the bam properly. Replicated in a local docker, and there are three issues that were happening with these regexes.
1. Perl seems to be reading the samtools results as a single string, not a collection of strings. The leading ^ to pin to start of string no longer works, because they're several lines down.
2. Somehow filter_vcf_dom.cwl was missing the .+ to span the line
3. filter_vcf_dom needs to escape the @. Unsure why mutect doesn't?
Error from the unmatched regex:
```
Use of uninitialized value $normal_name in concatenation (.) or string at docm_filter.pl line 19.
Use of uninitialized value $tumor_name in concatenation (.) or string at docm_filter.pl line 19.
```
Error from the …
> Correct parsing issues with sample name regex in mutect and filter_vcf_docm

- definitions/tools/bcftools_merge.cwl
- definitions/tools/filter_known_variants.cwl
- definitions/tools/filter_sv_vcf_depth.cwl
- definitions/tools/filter_sv_vcf_read_support.cwl
- definitions/tools/filter_sv_vcf_size.cwl
- definitions/tools/intersect_known_variants.cwl
- definitions/tools/merge_vcf.cwl
- definitions/tools/remove_end_tags.cwl
- definitions/tools/replace_vcf_sample_name.cwl
updating bcftools version for #948
version 1.9 to 1.12, release notes can be found [here](https://github.com/samtools/bcftools/releases)
One new feature is that the output type no longer needs to be specified. bcftools is able to determine the output type based on the suffix of the output file name.
> update bcftools version 1.12

- .github/workflows/main.yml
Since travis-ci.org is gone, we'll need a replacement.  This tries to faithfully reproduce the existing .travis.yml as a github workflow.  (If this works something similar needs to happen for the auto-documentation, too.
> Initial github action for testing

- definitions/tools/smoove.cwl
This PR upgrades smoove to the latest version and uses the working brentp docker image. 
#1034
> upgrade smoove to v0.2.7

- .github/workflows/update_docs.yml
On Travis the default info was enough to generate a commit, but github doesn't fill in enough info in its actions, so let's set up a name and email for ourselves!
> Set user name and email for documentation update commit.

- definitions/tools/add_strelka_gt.cwl
Sometimes we'll encounter entries which have a $gt_str which has
characters not contained in the $ids map. This results in malformed gt
entries, like `/0` or `1/` or `/`. When these entries occur,
downstream calls like merge_vcf (in the case of immuno workflow) will
print an error and _silently continue on their merry way_. I have no
idea why they do this, but it's something we noticed when testing
conversion over to WDL with HCC1395 sample.
We address this issue by checking the results of @gt_ids, and if any
are undefined we eject early, returning undefined. At the call site we
handle this case separate by printing to STDERR, dropping that line,
and moving on to the remainder.
An alternative approach of a more strict failure is an option, but
discussion with Chris Miller and Malachi …
> handle unparseable GT entries by skipping those lines

- definitions/tools/mutect.cwl
For broadinstitute/gatk:4.1.8.1 mutect calls variants that do not appear in IGV or pileup. Behaviour not seen in broadinstitute/gatk:4.2+
> v4.1.8.1 weird behaviour, not seen in v4.2+

- definitions/tools/sequence_to_fastq.cwl
- definitions/tools/trim_fastq.cwl
A small change to produce unique filenames from the flexbar tool step, so that GMS output staging doesn't fail when running the immuno pipeline.
> Keep sample names in filenames

- definitions/tools/filter_vcf_mapq0.cwl
This handles variants with no DP information.  (For more details, see genome/docker-mapq0-filter#8.)
> Upgrade mapq0 filter to v0.5.3

- definitions/pipelines/immuno.cwl
- definitions/subworkflows/generate_fda_metrics.cwl
- definitions/tools/aligned_seq_fda_stats.cwl
- definitions/tools/fastqc.cwl
- definitions/tools/fastqc_bam_metrics.cwl
- definitions/tools/generate_fda_tables.cwl
- definitions/tools/md5sum.cwl
- definitions/tools/unaligned_seq_fda_stats.cwl
This PR adds a new subworkflow to `immuno.cwl` which creates summary tables in csv format containing information requested by the FDA for clinical cases. Several new tools are introduced, including FastQC, which was specifically requested by the FDA, as well as custom scripts for both unaligned and aligned data to calculate requested metrics not generated by FastQC or other existing upstream tools (eg, picard, flagstat). A host of new inputs are added to the `immuno` workflow to gather requested sequencing and sample information (eg, sequencing instrument, total amount of DNA/RNA).
> Immuno FDA metrics

- definitions/tools/filter_vcf_mapq0.cwl
New version is https://hub.docker.com/layers/mgibio/mapq0-filter/v0.5.4/images/sha256-ef5046b3e74bd1689fbf599c2731031213f9436061f791b909bc77779e2137d2?context=explore
> Update docker image to 0.5.4 for handling of case of 0-depth variant.

- definitions/pipelines/immuno.cwl
- definitions/subworkflows/generate_fda_metrics.cwl
- definitions/tools/aligned_seq_fda_stats.cwl
- definitions/tools/generate_fda_tables.cwl
- definitions/tools/rename_for_staging.cwl
- definitions/tools/unaligned_seq_fda_stats.cwl
This PR introduces a CWL scatter across individual sequence elements (a bam or pair of fastqs) of the input array for each of the 3 unaligned inputs (normal DNA, tumor DNA, tumor RNA) when calculating statistics to be reported to the FDA in clinical cases. Previously, some statistics were calculated using data from all sequence files for an input at once, which is less accurate.
> Fda metrics split on sequence
